service: upselling-storefront-api-gateway
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 10
  endpointType: REGIONAL
  stage: ${env:STAGE, 'dev'}
  region: ${env:AWS_REGION, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    shouldStartNameWithService: true
  environment:
    LOG_QUEUE_URL: ${env:LOG_QUEUE_URL, ssm:/upselling/${self:provider.stage}/queues/log/url}
    LOG_SOURCE: 'storefront-api-gateway'
    SHOPS_API_URL: ${env:SHOPS_API_URL, ssm:/upselling/${self:provider.stage}/shops-api/url}

functions:
  health:
    handler: src/routes/health.handler
    events:
      - http:
          path: /health
          method: get
          cors: true
  region:
    handler: src/routes/region.handler
    events:
      - http:
          path: /region
          method: get
          cors: true
  findOneRandomOffer:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneRandomOffer.handler
    events:
      - http:
          path: /offers/random
          method: post
          cors: true
  findShop:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShop.handler
    events:
      - http:
          path: /shop
          method: get
          cors: true
  trackOfferAcceptance:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/trackOfferAcceptance.handler
    events:
      - http:
          path: /offers/{offerId}/acceptances
          method: post
          cors: true
  trackOfferImpression:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/trackOfferImpression.handler
    events:
      - http:
          path: /offers/{offerId}/impressions
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-monorepo
  - serverless-domain-manager

custom:
  serverless-offline:
    httpPort: ${env:STOREFRONT_API_GATEWAY_PORT}
    lambdaPort: 5001
  customDomain:
    domainName: ${ssm:/upselling/${self:provider.stage}/storefront-api-gateway/endpoint/${self:provider.region}}
    basePath: ''
    certificateName: ${ssm:/upselling/${self:provider.stage}/certificate-name}
    createRoute53Record: true
    endpointType: regional
    securityPolicy: tls_1_2

package:
  exclude:
    - test/**
    - node_modules/aws-sdk
    - node_modules/**/aws-sdk
    - node_modules/**/*.map
