- name: Create admin user account
  user:
    name: "{{ server_admin_user }}"
    password: "{{ server_admin_password | b64decode }}"
    groups:
      - sudo
    state: present
    shell: /bin/bash
    createhome: yes
    system: no

- name: Add authorized key for admin user account
  authorized_key:
    user: "{{ server_admin_user }}"
    state: present
    key: "{{ server_admin_key | b64decode }}"
