service: upselling-shop-api-gateway

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 10
  endpointType: REGIONAL
  stage: ${env:STAGE, 'dev'}
  region: ${env:AWS_REGION, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    shouldStartNameWithService: true
  environment:
    AWS_ENDPOINT: ${env:AWS_ENDPOINT}
    JWT_SECRET: ${env:JWT_SECRET, ssm:/upselling/${self:provider.stage}/jwt-secret~true}
    LOG_QUEUE_URL: ${env:LOG_QUEUE_URL, ssm:/upselling/${self:provider.stage}/queues/log/url}
    SHOPS_API_URL: ${env:SHOPS_API_URL, ssm:/upselling/${self:provider.stage}/shops-api/url}
    LOG_SOURCE: 'shop-api-gateway'

functions:
  authorizer:
    handler: src/authorizer.handler
  health:
    handler: src/routes/health.handler
    events:
      - http:
          path: /health
          method: get
          cors: true
  region:
    handler: src/routes/region.handler
    events:
      - http:
          path: /region
          method: get
          cors: true
  createOffer:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/createOffer.handler
    events:
      - http:
          path: /offers
          method: post
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
  deleteOffer:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/deleteOffer.handler
    events:
      - http:
          path: /offers/{offerId}
          method: delete
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
  findOffers:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOffers.handler
    events:
      - http:
          path: /offers
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
  findOneOffer:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneOffer.handler
    events:
      - http:
          path: /offers/{offerId}
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
  updateOffer:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updateOffer.handler
    events:
      - http:
          path: /offers/{offerId}
          method: put
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
  findOfferAcceptances:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferAcceptances.handler
    events:
      - http:
          path: /offers/{offerId}/acceptances
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
  findOfferConversionRates:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferConversionRates.handler
    events:
      - http:
          path: /offers/{offerId}/conversion-rates
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
  findOfferConversions:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferConversions.handler
    events:
      - http:
          path: /offers/{offerId}/conversions
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
  findOfferRevenueIncreases:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferRevenueIncreases.handler
    events:
      - http:
          path: /offers/{offerId}/revenue-increases
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
  findOfferViews:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferViews.handler
    events:
      - http:
          path: /offers/{offerId}/views
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
  findOneShop:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneShop.handler
    events:
      - http:
          path: /shop
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
  updateShop:
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updateShop.handler
    events:
      - http:
          path: /shop
          method: put
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-ngrok-tunnel
  - serverless-plugin-monorepo
  - serverless-domain-manager

custom:
  dotenv:
    path: .env
    logging: false
  serverless-offline:
    httpPort: ${env:SHOP_API_GATEWAY_PORT}
    lambdaPort: 5000
  ngrokTunnel:
    tunnels:
      - port: ${env:SHOP_API_GATEWAY_PORT}
        ngrokOptions:
          authToken: ${env:NGROK_AUTH_TOKEN}
          region: ${env:NGROK_REGION}
          subdomain: ${env:SHOP_API_GATEWAY_TUNNEL_SUBDOMAIN}
      - port: ${env:SHOPIFY_ADMIN_APP_PORT}
        ngrokOptions:
          authToken: ${env:NGROK_AUTH_TOKEN}
          region: ${env:NGROK_REGION}
          subdomain: ${env:SHOPIFY_ADMIN_APP_SUBDOMAIN}
  customDomain:
    domainName: ${ssm:/upselling/${self:provider.stage}/shop-api-gateway/endpoint/${self:provider.region}}
    basePath: ''
    certificateName: ${ssm:/upselling/${self:provider.stage}/certificate-name}
    createRoute53Record: true
    endpointType: regional
    securityPolicy: tls_1_2

package:
  exclude:
    - test/**
    - node_modules/aws-sdk
    - node_modules/**/aws-sdk
    - node_modules/**/*.map
