# Reference: https://github.com/PharosProduction/tutorial-mongodb-ansible
# Reference: https://sebworks.com/securing-mongodb-tls-auth-letsencrypt/

- name: Determine if MongoDB is installed
  stat:
    path: /usr/bin/mongod
  register: mongodb

- name: Add Mongo PPA key
  raw: curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor
  when: not mongodb.stat.exists

- name: Add Mongo sources list
  lineinfile:
    line: 'deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse'
    dest: /etc/apt/sources.list.d/mongodb-org-8.0.list
    state: present
    create: yes
  when: not mongodb.stat.exists

- name: Update apt cache
  apt:
    update_cache: yes
  when: not mongodb.stat.exists

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
    cache_valid_time: 3600
    allow_unauthenticated: yes
  when: not mongodb.stat.exists

- name: Hold MongoDB packages
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  loop:
    - mongodb-org
    - mongodb-org-server
    - mongodb-org-shell
    - mongodb-org-mongos
    - mongodb-mongosh
    - mongodb-org-tools
  when: not mongodb.stat.exists

- name: Ensure MongoDB is enabled to start automatically on boot
  systemd:
    name: mongod
    enabled: yes
    state: started
  when: not mongodb.stat.exists

- name: Create MongoDB root user
  mongodb_user:
    database: admin
    name: root
    password: '{{ mongodb_root_password }}'
    update_password: on_create
    roles:
      - role: root
    ssl: true
    ssl_cert_reqs: CERT_NONE
  ignore_errors: false
  when: not mongodb.stat.exists

- name: Regenerate certificate files
  command: /root/update-certificates.sh
  when: not mongodb.stat.exists

- name: Create MongoDB config file
  copy:
    src: mongod.conf
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
  when: not mongodb.stat.exists

- name: Create /etc/security/limits.d/mongod.conf
  copy:
    src: security-mongod.conf
    dest: /etc/security/limits.d/mongod.conf
    owner: root
    group: root
    mode: 0644
  when: not mongodb.stat.exists

- name: Restart MongoDB
  service:
    name: mongod.service
    state: restarted
  when: not mongodb.stat.exists

- name: Set up a job for Shops database backup
  cron:
    name: backup-shops-database
    minute: '0'
    hour: '0,6,12,18'
    user: root
    job: "/usr/bin/mongodump --archive --uri 'mongodb://backup:{{ mongodb_backup_password }}@{{ services_domain }}/greatupsells-shops?ssl=true' | /usr/bin/gzip -9 -c | /usr/local/bin/aws s3 cp - s3://greatupsells-backups2/database/{{ stage }}/greatupsells-shops/$(date +\\%s).gz --storage-class STANDARD_IA"
  when: region == "us-east-1"

- name: Set up a job for Logs database backup
  cron:
    name: backup-logs-database
    minute: '1'
    hour: '0,6,12,18'
    user: root
    job: "/usr/bin/mongodump --archive --uri 'mongodb://backup:{{ mongodb_backup_password }}@{{ services_domain }}/greatupsells-logs?ssl=true' | /usr/bin/gzip -9 -c | /usr/local/bin/aws s3 cp - s3://greatupsells-backups2/database/{{ stage }}/greatupsells-logs/$(date +\\%s).gz --storage-class STANDARD_IA"
  when: region == "us-east-1"

- name: Create MongoDB admin user account
  community.mongodb.mongodb_user:
    login_host: '{{ services_domain }}'
    login_database: admin
    login_user: root
    login_password: '{{ mongodb_root_password }}'
    database: admin
    name: chad
    password: '{{ mongodb_admin_password }}'
    roles:
      - { role: 'userAdminAnyDatabase', db: 'admin' }
      - dbAdminAnyDatabase
      - readWriteAnyDatabase
    ssl: true
    state: present
  when:
    - region == "us-east-1"

- name: Create MongoDB app user account for greatupsells-shops
  community.mongodb.mongodb_user:
    login_host: '{{ services_domain }}'
    login_database: admin
    login_user: root
    login_password: '{{ mongodb_root_password }}'
    database: greatupsells-shops
    name: app
    password: '{{ mongodb_app_password }}'
    roles:
      - { role: 'dbAdmin', db: 'greatupsells-shops' }
      - { role: 'readWrite', db: 'greatupsells-shops' }
    ssl: true
    state: present
  when:
    - region == "us-east-1"

- name: Create MongoDB app user account for greatupsells-logs
  community.mongodb.mongodb_user:
    login_host: '{{ services_domain }}'
    login_database: admin
    login_user: root
    login_password: '{{ mongodb_root_password }}'
    database: greatupsells-logs
    name: app
    password: '{{ mongodb_app_password }}'
    roles:
      - { role: 'dbAdmin', db: 'greatupsells-logs' }
      - { role: 'readWrite', db: 'greatupsells-logs' }
    ssl: true
    state: present
  when:
    - region == "us-east-1"

- name: Create MongoDB backup user account
  community.mongodb.mongodb_user:
    login_host: '{{ services_domain }}'
    login_database: admin
    login_user: root
    login_password: '{{ mongodb_root_password }}'
    database: admin
    name: backup
    password: '{{ mongodb_backup_password }}'
    roles:
      - { role: 'read', db: 'greatupsells-shops' }
      - { role: 'read', db: 'greatupsells-logs' }
    ssl: true
    state: present
  when:
    - region == "us-east-1"
