# Reference: https://github.com/PharosProduction/tutorial-mongodb-ansible
# Reference: https://sebworks.com/securing-mongodb-tls-auth-letsencrypt/

- name: Determine if MongoDB is installed
  stat:
    path: /usr/bin/mongod
  register: mongodb

- name: Add Mongo PPA key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present
  when: not mongodb.stat.exists

- name: Add Mongo sources list
  lineinfile:
    line: 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse'
    dest: /etc/apt/sources.list.d/mongodb-org-4.4.list
    state: present
    create: yes
  when: not mongodb.stat.exists

- name: Update apt cache
  apt:
    update_cache: yes
  when: not mongodb.stat.exists

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
    cache_valid_time: 3600
    allow_unauthenticated: yes
  when: not mongodb.stat.exists

- name: Hold MongoDB packages
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  loop:
    - mongodb-org
    - mongodb-org-server
    - mongodb-org-shell
    - mongodb-org-mongos
    - mongodb-org-tools
  when: not mongodb.stat.exists

- name: Ensure mongodb is running and enabled to start automatically on reboot
  systemd:
    name: mongod
    enabled: yes
    state: started
  when: not mongodb.stat.exists

- name: Create MongoDB root user
  mongodb_user:
    database: admin
    name: root
    password: '{{ mongodb_root_password }}'
    update_password: on_create
    roles: root
  ignore_errors: yes
  when: not mongodb.stat.exists

- name: Regenerate certificate files
  command: /root/update-certificates.sh
  when: not mongodb.stat.exists

- name: Create MongoDB config file
  copy:
    src: mongod.conf
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
  when: not mongodb.stat.exists

- name: Create /etc/security/limits.d/mongod.conf
  copy:
    src: security-mongod.conf
    dest: /etc/security/limits.d/mongod.conf
    owner: root
    group: root
    mode: 0644
  when: not mongodb.stat.exists

- name: Start MongoDB
  service:
    name: mongod.service
    state: restarted
  when: not mongodb.stat.exists

- name: Set up a job for Shops database backup
  cron:
    name: backup-shops-database
    minute: "0"
    hour: "0,6,12,18"
    user: root
    job: "/usr/bin/mongodump --archive --uri 'mongodb://backup:{{ mongodb_backup_password }}@{{ domain_name }}/greatupsells-shops?replicaSet=rs0&readPreference=secondaryPreferred&ssl=true' --sslAllowInvalidCertificates | /usr/bin/gzip -9 -c | /usr/local/bin/aws s3 cp - s3://greatupsells-backups/database/{{ stage }}/greatupsells-shops/$(date +\\%s).gz --storage-class STANDARD_IA"
  when: region == "us-east-1"

- name: Set up a job for Logs database backup
  cron:
    name: backup-logs-database
    minute: "1"
    hour: "0,6,12,18"
    user: root
    job: "/usr/bin/mongodump --archive --uri 'mongodb://backup:{{ mongodb_backup_password }}@{{ domain_name }}/greatupsells-logs?replicaSet=rs0&readPreference=secondaryPreferred&ssl=true' --sslAllowInvalidCertificates | /usr/bin/gzip -9 -c | /usr/local/bin/aws s3 cp - s3://greatupsells-backups/database/{{ stage }}/greatupsells-logs/$(date +\\%s).gz --storage-class STANDARD_IA"
  when: region == "us-east-1"

- name: Read MongoDB status
  shell: |
    mongo --host {{ domain_name }} -u root -p {{ mongodb_root_password }} --tls --sslAllowInvalidCertificates --eval 'rs.status()' --quiet
  changed_when: false
  ignore_errors: true
  register: mongodb_info
  when: region == "us-east-1"

- name: "Initiate MongoDB replica set (test)"
  shell: |
    mongo --host {{ domain_name }} -u root -p {{ mongodb_root_password }} --tls --sslAllowInvalidCertificates --quiet --eval ' \
      rs.initiate({
        _id : "rs0",
        members: [
          { _id: 0, host: "services.test.greatupsells.com:27017" }
        ]
      })
    '
  when:
    - region == "us-east-1"
    - stage == "test"
    - "'NotYetInitialized' in mongodb_info.stdout"

- name: "Initiate MongoDB replica set (production)"
  shell: |
    mongo --host {{ domain_name }} -u root -p {{ mongodb_root_password }} --tls --sslAllowInvalidCertificates --quiet --eval ' \
      rs.initiate({
        _id : "rs0",
        members: [
          { _id: 0, host: "services.us-east-1.greatupsells.com:27017" },
          { _id: 1, host: "services.us-west-2.greatupsells.com:27017" },
          { _id: 2, host: "services.us-east-2.greatupsells.com:27017" },
          { _id: 3, host: "services.eu-west-1.greatupsells.com:27017" },
          { _id: 4, host: "services.ap-northeast-1.greatupsells.com:27017" }
        ]
      })
    '
  when:
    - region == "us-east-1"
    - stage == "production"
    - "'NotYetInitialized' in mongodb_info.stdout"

- name: Configure replica set hosts
  shell: |
    mongo --host {{ domain_name }} -u root -p {{ mongodb_root_password }} --tls --sslAllowInvalidCertificates --quiet --eval ' \
      config = rs.conf()
      config.members[0].priority = 0.5
      config.members[1].priority = 0.5
      config.members[2].priority = 1
      config.members[3].priority = 0
      config.members[3].votes = 0
      config.members[4].priority = 0
      config.members[4].votes = 0
      rs.reconfig(config)
    '
  when:
    - region == "us-east-1"
    - stage == "production"
    - "'NotYetInitialized' in mongodb_info.stdout"

- name: Create admin user account
  shell: |
    mongo --host {{ domain_name }} -u root -p {{ mongodb_root_password }} --tls --sslAllowInvalidCertificates --quiet --eval ' \
      use admin
      db.createUser({
        user: "chad",
        pwd: "{{ mongodb_admin_password }}",
        roles: [ { role: "userAdminAnyDatabase", db: "admin" }, "readWriteAnyDatabase" ]
      })
    '
  when:
    - region == "us-east-1"
    - "'NotYetInitialized' in mongodb_info.stdout"

- name: Create app user account for shops database
  shell: |
    mongo --host {{ domain_name }} -u root -p {{ mongodb_root_password }} --tls --sslAllowInvalidCertificates --quiet --eval ' \
      use greatupsells-shops
      db.createUser({
        user: "app",
        pwd: "{{ mongodb_app_password }}",
        roles: [ { role: "readWrite", db: "greatupsells-shops" } ]
      })
    '
  when:
    - region == "us-east-1"
    - "'NotYetInitialized' in mongodb_info.stdout"

- name: Create app user account for logs database
  shell: |
    mongo --host {{ domain_name }} -u root -p {{ mongodb_root_password }} --tls --sslAllowInvalidCertificates --quiet --eval ' \
      use greatupsells-logs
      db.createUser({
        user: "app",
        pwd: "{{ mongodb_app_password }}",
        roles: [ { role: "readWrite", db: "greatupsells-logs" } ]
      })
    '
  when:
    - region == "us-east-1"
    - "'NotYetInitialized' in mongodb_info.stdout"

- name: Create backup user account for shops database
  shell: |
    mongo --host {{ domain_name }} -u root -p {{ mongodb_root_password }} --tls --sslAllowInvalidCertificates --quiet --eval ' \
      use greatupsells-shops
      db.createUser({
        user: "backup",
        pwd: "{{ mongodb_backup_password }}",
        roles: [ { role: "readWrite", db: "greatupsells-shops" } ]
      })
    '
  when:
    - region == "us-east-1"
    - "'NotYetInitialized' in mongodb_info.stdout"

- name: Create backup user account for logs database
  command: |
    mongo --host {{ domain_name }} -u root -p {{ mongodb_root_password }} --tls --sslAllowInvalidCertificates --quiet --eval ' \
      use greatupsells-logs
      db.createUser({
        user: "backup",
        pwd: "{{ mongodb_backup_password }}",
        roles: [ { role: "readWrite", db: "greatupsells-logs" } ]
      })
    '
  when:
    - region == "us-east-1"
    - "'NotYetInitialized' in mongodb_info.stdout"
