service: upselling-workers

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 900
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  environment:
    MONGODB_URI: ${ssm:/upselling/${self:provider.stage}/database/mongodb/uri~true}

functions:
  shopCollectionImport:
    reservedConcurrency: 10
    handler: shopCollectionImport.handler
    events:
      - sqs:
          arn: ${ssm:/upselling/${self:provider.stage}/shop-collection-import-queue-arn}

  shopProductImport:
    reservedConcurrency: 10
    handler: shopProductImport.handler
    events:
      - sqs:
          arn: ${ssm:/upselling/${self:provider.stage}/shop-product-import-queue-arn}

plugins:
  - serverless-plugin-monorepo

package:
  exclude:
    - test/**
    - node_modules/aws-sdk
    - node_modules/**/aws-sdk
    - node_modules/**/*.map
