service: upselling-shops-service
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    shouldStartNameWithService: true
    resourcePolicy: # https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_SPECIFIC_KEYS
      - Effect: Allow
        Principal:
          AWS: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
        Action: execute-api:Invoke
        Resource: "*"
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource: "execute-api:/*/GET/health"
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    ASSETS_URL: ${env:ASSETS_URL, ssm:/upselling/${self:provider.stage}/assets/url}
    LOG_QUEUE_URL: ${env:LOG_QUEUE_URL, ssm:/upselling/${self:provider.stage}/queues/log/url}
    LOG_SOURCE: 'shops-service'
    LOGS_API_URL: ${env:LOGS_API_URL, ssm:/upselling/${self:provider.stage}/logs-api/url}
    MONGODB_URI_SHOPS: ${env:MONGODB_URI_SHOPS, ssm:/upselling/${self:provider.stage}/database/mongodb-shops/uri}
    SANDBOX: ${env:SANDBOX, ssm:/upselling/${self:provider.stage}/sandbox}
    SHOPIFY_ADMIN_APP_API_KEY: ${env:SHOPIFY_ADMIN_APP_API_KEY, ssm:/upselling/${self:provider.stage}/shopify/api-key}
    SHOP_COLLECTION_IMPORT_QUEUE_URL: ${env:SHOP_COLLECTION_IMPORT_QUEUE_URL, ssm:/upselling/${self:provider.stage}/queues/shop-collection-import/url}
    SHOP_PRODUCT_IMPORT_QUEUE_URL: ${env:SHOP_PRODUCT_IMPORT_QUEUE_URL, ssm:/upselling/${self:provider.stage}/queues/shop-product-import/url}
    WEBHOOK_API_URL: ${env:WEBHOOK_API_URL}
    WEBHOOK_ARN: ${env:WEBHOOK_ARN, ssm:/upselling/${self:provider.stage}/webhooks/arn}

functions:
  addDraftOrderLineItem:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/addDraftOrderLineItem.handler
    events:
      - http:
          path: /shops/{shopId}/draft-orders/{draftOrderId}/line-items
          method: post
          authorizer: aws_iam
  cancelOrder:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/cancelOrder.handler
    events:
      - http:
          path: /orders/{orderId}/cancelation
          method: post
          authorizer: aws_iam
  cloneOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/cloneOffer.handler
    events:
      - http:
          path: /offers/{offerId}/clone
          method: post
          authorizer: aws_iam
  clonePopupTheme:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/clonePopupTheme.handler
    events:
      - http:
          path: /popup-themes/{popupThemeId}/clone
          method: post
          authorizer: aws_iam
  createCollection:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/createCollection.handler
    events:
      - http:
          path: /collections
          method: post
          authorizer: aws_iam
  createDraftOrder:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/createDraftOrder.handler
    events:
      - http:
          path: /shops/{shopId}/draft-orders
          method: post
          authorizer: aws_iam
  createOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/createOffer.handler
    events:
      - http:
          path: /offers
          method: post
          authorizer: aws_iam
  createOrder:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/createOrder.handler
    events:
      - http:
          path: /orders
          method: post
          authorizer: aws_iam
  createPopupTheme:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/createPopupTheme.handler
    events:
      - http:
          path: /popup-themes
          method: post
          authorizer: aws_iam
  createProduct:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/createProduct.handler
    events:
      - http:
          path: /products
          method: post
          authorizer: aws_iam
  deactivateShop:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/deactivateShop.handler
    events:
      - http:
          path: /shops/{shopId}/deactivation
          method: post
          authorizer: aws_iam
  deleteCollection:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/deleteCollection.handler
    events:
      - http:
          path: /collections/{collectionId}
          method: delete
          authorizer: aws_iam
  deleteOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/deleteOffer.handler
    events:
      - http:
          path: /offers/{offerId}
          method: delete
          authorizer: aws_iam
  deleteProduct:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/deleteProduct.handler
    events:
      - http:
          path: /products/{productId}
          method: delete
          authorizer: aws_iam
  findOfferAcceptances:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferAcceptances.handler
    events:
      - http:
          path: /offers/{offerId}/acceptances
          method: get
          authorizer: aws_iam
  findOfferConversionRates:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferConversionRates.handler
    events:
      - http:
          path: /offers/{offerId}/conversion-rates
          method: get
          authorizer: aws_iam
  findOfferImpressions:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferImpressions.handler
    events:
      - http:
          path: /offers/{offerId}/impressions
          method: get
          authorizer: aws_iam
  findOfferConversions:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferConversions.handler
    events:
      - http:
          path: /offers/{offerId}/conversions
          method: get
          authorizer: aws_iam
  findOfferRevenueIncreases:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferRevenueIncreases.handler
    events:
      - http:
          path: /offers/{offerId}/revenue-increases
          method: get
          authorizer: aws_iam
  findPopupThemes:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findPopupThemes.handler
    events:
      - http:
          path: /popup-themes
          method: get
          authorizer: aws_iam
  findShopAcceptances:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopAcceptances.handler
    events:
      - http:
          path: /shops/{shopId}/acceptances
          method: get
          authorizer: aws_iam
  findShopConversionRates:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopConversionRates.handler
    events:
      - http:
          path: /shops/{shopId}/conversion-rates
          method: get
          authorizer: aws_iam
  findShopConversions:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopConversions.handler
    events:
      - http:
          path: /shops/{shopId}/conversions
          method: get
          authorizer: aws_iam
  findShopImpressions:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopImpressions.handler
    events:
      - http:
          path: /shops/{shopId}/impressions
          method: get
          authorizer: aws_iam
  findShopRevenueIncreases:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopRevenueIncreases.handler
    events:
      - http:
          path: /shops/{shopId}/revenue-increases
          method: get
          authorizer: aws_iam
  findOfferPopupThemes:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferPopupThemes.handler
    events:
      - http:
          path: /offers/{offerId}/popup-themes
          method: get
          authorizer: aws_iam
  findOffers:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOffers.handler
    events:
      - http:
          path: /offers
          method: get
          authorizer: aws_iam
  findOneCollectionId:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneCollectionId.handler
    events:
      - http:
          path: /collections/shopify-collection-id/{shopifyCollectionId}
          method: get
          authorizer: aws_iam
  findOneOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneOffer.handler
    events:
      - http:
          path: /offers/{offerId}
          method: get
          authorizer: aws_iam
  findOneOrder:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneOrder.handler
    events:
      - http:
          path: /orders/{orderId}
          method: get
          authorizer: aws_iam
  findOneOrderByShopifyOrderId:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneOrderByShopifyOrderId.handler
    events:
      - http:
          path: /orders/shopify-order-id/{shopifyOrderId}
          method: get
          authorizer: aws_iam
  findOnePopupTheme:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOnePopupTheme.handler
    events:
      - http:
          path: /popup-themes/{popupThemeId}
          method: get
          authorizer: aws_iam
  findOneProductByShopifyProductId:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneProductByShopifyProductId.handler
    events:
      - http:
          path: /products/shopify-product-id/{shopifyProductId}
          method: get
          authorizer: aws_iam
  findOneRandomShopOfferByDomain:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneRandomShopOfferByDomain.handler
    events:
      - http:
          path: /shops/domain/{domain}/offers/random
          method: post
          authorizer: aws_iam
  findOneShop:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneShop.handler
    events:
      - http:
          path: /shops/{shopId}
          method: get
          authorizer: aws_iam
  findOneShopByDomain:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneShopByDomain.handler
    events:
      - http:
          path: /shops/domain/{domain}
          method: get
          authorizer: aws_iam
  findShopOffers:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopOffers.handler
    events:
      - http:
          path: /shops/{shopId}/offers
          method: get
          authorizer: aws_iam
  findShopPopupThemes:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopPopupThemes.handler
    events:
      - http:
          path: /shops/{shopId}/popup-themes
          method: get
          authorizer: aws_iam
  health:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/health.handler
    events:
      - http:
          path: /health
          method: get
  initializeShopByDomain:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/initializeShopByDomain.handler
    timeout: 20
    events:
      - http:
          path: /shops/domain/{domain}/initialization
          method: post
          authorizer: aws_iam
  region:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/region.handler
    events:
      - http:
          path: /region
          method: get
  trackOfferAcceptance:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/trackOfferAcceptance.handler
    events:
      - http:
          path: /offers/{offerId}/acceptances
          method: post
          authorizer: aws_iam
  trackOfferImpression:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/trackOfferImpression.handler
    events:
      - http:
          path: /offers/{offerId}/impressions
          method: post
          authorizer: aws_iam
  updateCollection:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updateCollection.handler
    events:
      - http:
          path: /collections/{collectionId}
          method: put
          authorizer: aws_iam
  updateShopifyDraftOrder:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updateShopifyDraftOrder.handler
    events:
      - http:
          path: /shops/{shopId}/draft-orders/{draftOrderId}/line-items/{shopifyVariantId}
          method: post
          authorizer: aws_iam
  updateOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updateOffer.handler
    events:
      - http:
          path: /offers/{offerId}
          method: put
          authorizer: aws_iam
  updateOrder:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updateOrder.handler
    events:
      - http:
          path: /orders/{orderId}
          method: put
          authorizer: aws_iam
  updatePopupTheme:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updatePopupTheme.handler
    events:
      - http:
          path: /popup-themes/{popupThemeId}
          method: put
          authorizer: aws_iam
  updateProduct:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updateProduct.handler
    events:
      - http:
          path: /products/{productId}
          method: put
          authorizer: aws_iam
  updateShop:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updateShop.handler
    events:
      - http:
          path: /shops/{shopId}
          method: put
          authorizer: aws_iam
  calculateStats:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/calculateStats.handler
    events:
      - schedule: cron(1 5,6 * * ? *)
    timeout: 900
    enabled: '"${self:provider.region}" == "us-east-1"'
  fixShopWebhooks:
    memorySize: 512
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/fixShopWebhooks.handler
    events:
      - schedule: rate(1 day)
    timeout: 900
    enabled: '"${self:provider.region}" == "us-east-1"'
  importShopCollections:
    memorySize: 512
    reservedConcurrency: 5
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/importShopCollections.handler
    events:
      - sqs:
          arn: ${env:SHOP_COLLECTION_IMPORT_QUEUE_ARN, ssm:/upselling/${self:provider.stage}/queues/shop-product-import/arn}
    timeout: 900
  importShopProducts:
    memorySize: 512
    reservedConcurrency: 5
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/importShopProducts.handler
    events:
      - sqs:
          arn: ${env:SHOP_PRODUCT_IMPORT_QUEUE_ARN, ssm:/upselling/${self:provider.stage}/queues/shop-product-import/arn}
    timeout: 900
  updateShopActiveStatuses:
    memorySize: 512
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/updateShopActiveStatuses.handler
    events:
      - schedule: rate(1 day)
    timeout: 900
    enabled: '"${self:provider.region}" == "us-east-1"'
  updateShopPlans:
    memorySize: 512
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/updateShopPlans.handler
    events:
      - schedule: rate(1 day)
    timeout: 900
    enabled: '"${self:provider.region}" == "us-east-1"'

plugins:
  - serverless-offline
  - serverless-plugin-monorepo
  - serverless-domain-manager
  - serverless-plugin-conditional-functions

custom:
  serverless-offline:
    httpPort: ${env:SHOPS_API_PORT, 4004}
    lambdaPort: 5002
  customDomain:
    domainName: ${env:SHOPS_API_DOMAIN, ssm:/upselling/${self:provider.stage}/shops-api/regional-domain}
    basePath: ''
    certificateName: ${env:CERTIFICATE_NAME, ssm:/upselling/${self:provider.stage}/certificate-name}
    createRoute53Record: true
    endpointType: regional
    securityPolicy: tls_1_2
    autoDomain: true

package:
  exclude:
    - infrastructure/**
