service: upselling-shops-service

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 900
  endpointType: REGIONAL
  stage: ${env:STAGE, 'dev'}
  region: ${env:AWS_REGION, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    shouldStartNameWithService: true
  environment:
    # APP_SLUG: upselling
    # SHOPIFY_ADMIN_API_KEY: ${env:SHOPIFY_ADMIN_API_KEY, ssm:/upselling/${self:provider.stage}/shopify-admin/api-key}
    # SHOPIFY_ADMIN_URL: ${env:SHOPIFY_ADMIN_URL, ssm:/upselling/${self:provider.stage}/shopify-admin/url}
    # API_URL: ${env:API_URL, ssm:/upselling/${self:provider.stage}/api/url}
    # CONTACT_EMAIL: ${env:CONTACT_EMAIL, ssm:/upselling/${self:provider.stage}/contact-email}
    # SANDBOX: ${env:SANDBOX, ssm:/upselling/${self:provider.stage}/sandbox}
    # MONGODB_URI: ${env:MONGODB_URI, ssm:/upselling/${self:provider.stage}/database/mongodb/uri~true}
    LOG_QUEUE_URL: ${env:LOG_QUEUE_URL, ssm:/upselling/${self:provider.stage}/log-queue-url}

functions:
  health:
    handler: src/routes/health.handler
    events:
      - http:
          path: /health
          method: get
          cors: true
  region:
    handler: src/routes/region.handler
    events:
      - http:
          path: /region
          method: get
          cors: true
  createOffer:
    handler: src/routes/createOffer.handler
    events:
      - http:
          path: /offers
          method: post
  deleteOffer:
    handler: src/routes/deleteOffer.handler
    events:
      - http:
          path: /offers
          method: delete
  findOffers:
    handler: src/routes/findOffers.handler
    events:
      - http:
          path: /offers
          method: get
  findOneOffer:
    handler: src/routes/findOneOffer.handler
    events:
      - http:
          path: /offers/{offerId}
          method: get
  updateOffer:
    handler: src/routes/updateOffer.handler
    events:
      - http:
          path: /offers/{offerId}
          method: put
  trackOfferAcceptance:
    handler: src/routes/trackOfferAcceptance.handler
    events:
      - http:
          path: /offers/{offerId}/acceptances
          method: post
  findOfferAcceptances:
    handler: src/routes/findOfferAcceptances.handler
    events:
      - http:
          path: /offers/{offerId}/acceptances
          method: get
  findOfferConversionRates:
    handler: src/routes/findOfferConversionRates.handler
    events:
      - http:
          path: /offers/{offerId}/conversion-rates
          method: get
  findOfferConversions:
    handler: src/routes/findOfferConversions.handler
    events:
      - http:
          path: /offers/{offerId}/conversions
          method: get
  findOfferRevenueIncreases:
    handler: src/routes/findOfferRevenueIncreases.handler
    events:
      - http:
          path: /offers/{offerId}/revenue-increases
          method: get
  trackOfferView:
    handler: src/routes/trackOfferView.handler
    events:
      - http:
          path: /offers/{offerId}/views
          method: post
  findOfferViews:
    handler: src/routes/findOfferViews.handler
    events:
      - http:
          path: /offers/{offerId}/views
          method: get
  findOneRandomOfferProduct:
    handler: src/routes/findOneRandomOfferProduct.handler
    events:
      - http:
          path: /offers/{offerId}/products/random
          method: get
  findOneShop:
    handler: src/routes/findOneShop.handler
    events:
      - http:
          path: /shops/{shopId}
          method: get
  findOneShopByDomain:
    handler: src/routes/findOneShopByDomain.handler
    events:
      - http:
          path: /shops/domain/{domain}
          method: get
  updateShop:
    handler: src/routes/updateShop.handler
    events:
      - http:
          path: /shops/{shopId}
          method: put
  findShopOffers:
    handler: src/routes/findShopOffers.handler
    events:
      - http:
          path: /shops/{shopId}/offers
          method: get
  findOneRandomShopOffer:
    handler: src/routes/findOneRandomShopOffer.handler
    events:
      - http:
          path: /shops/{shopId}/offers/random
          method: get

  activateAndDeactivateShops:
    handler: src/workers/activateAndDeactivateShops.handler
    events:
      - schedule: rate(1 day)
  calculateStats:
    handler: src/workers/calculateStats.handler
    events:
      - schedule: cron(1 5,6 * * *)
  fixShopWebhooks:
    handler: src/workers/fixShopWebhooks.handler
    events:
      - schedule: rate(1 day)
  removeCopiedProducts:
    handler: src/workers/removeCopiedProducts.handler
    events:
      - schedule: rate(1 day)
  shopCollectionImport:
    reservedConcurrency: 10
    handler: src/workers/shopCollectionImport.handler
    events:
      - sqs:
          arn: ${ssm:/upselling/${self:provider.stage}/shop-collection-import-queue-arn}
  shopProductImport:
    reservedConcurrency: 10
    handler: src/workers/shopProductImport.handler
    events:
      - sqs:
          arn: ${ssm:/upselling/${self:provider.stage}/shop-product-import-queue-arn}
  updateShopPlans:
    handler: src/workers/updateShopPlans.handler
    events:
      - schedule: rate(1 day)

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-offline-sqs-external
  - serverless-plugin-monorepo

custom:
  dotenv:
    path: .env
  serverless-offline:
    httpPort: ${env:SHOPS_API_PORT}
  customDomain:
    domainName: ${ssm:/upselling/${self:provider.stage}/shops-service-api/endpoint/${self:provider.region}}
    basePath: ''
    certificateName: ${ssm:/upselling/${self:provider.stage}/certificate-name}
    createRoute53Record: true
    endpointType: regional
    securityPolicy: tls_1_2

package:
  exclude:
    - test/**
    - node_modules/aws-sdk
    - node_modules/**/aws-sdk
    - node_modules/**/*.map
