service: greatupsells-storefront-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 10
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    shouldStartNameWithService: true
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    LOGS_API_URL: ${env:LOGS_API_URL, ssm:/greatupsells/${self:provider.stage}/logs-api/url}
    LOG_QUEUE_URL: ${ssm:/greatupsells/${self:provider.stage}/queues/log/url, ''}
    LOG_SOURCE: 'storefront-api'
    SHOPS_API_URL: ${env:SHOPS_API_URL, ssm:/greatupsells/${self:provider.stage}/shops-api/url}

custom:
  serverless-offline:
    httpPort: ${env:STOREFRONT_API_PORT, 4006}
    lambdaPort: 4106
  customDomain:
    domainName: ${ssm:/greatupsells/${self:provider.stage}/storefront-api/domain, ''}
    basePath: ''
    certificateName: ${ssm:/greatupsells/${self:provider.stage}/certificate-name, ''}
    createRoute53Record: true
    endpointType: regional
    route53Params:
      routingPolicy: latency
      setIdentifier: ${self:provider.region}
      healthCheckId: ${ssm:/greatupsells/${self:provider.stage}/storefront-api/health-check-id, ''}
    securityPolicy: tls_1_2
    autoDomain: true
  warmup:
    default:
      enabled: false
      concurrency: 5
      prewarm: false
      events:
        - schedule: rate(5 minutes)

functions:
  health:
    memorySize: 128
    handler: src/routes/health.handler
    events:
      - http:
          path: /health
          method: get
          cors: true
    warmup:
      default:
        enabled: false
  region:
    memorySize: 128
    handler: src/routes/region.handler
    events:
      - http:
          path: /region
          method: get
          cors: true
    warmup:
      default:
        enabled: false
  addDraftOrderLineItem:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/addDraftOrderLineItem.handler
    events:
      - http:
          path: /draft-orders/{draftOrderId}/line-items
          method: post
          cors: true
  createDraftOrder:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/createDraftOrder.handler
    events:
      - http:
          path: /draft-orders
          method: post
          cors: true
  findOneRandomOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneRandomOffer.handler
    events:
      - http:
          path: /offers/random
          method: post
          cors: true
  findShop:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShop.handler
    events:
      - http:
          path: /shop
          method: get
          cors: true
  trackOfferAcceptance:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/trackOfferAcceptance.handler
    events:
      - http:
          path: /offers/{offerId}/acceptances
          method: post
          cors: true
  trackOfferImpression:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/trackOfferImpression.handler
    events:
      - http:
          path: /offers/{offerId}/impressions
          method: post
          cors: true
  updateShopifyDraftOrder:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updateShopifyDraftOrder.handler
    events:
      - http:
          path: /draft-orders/{draftOrderId}/line-items/{shopifyVariantId}
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-monorepo
  - serverless-domain-manager
  - serverless-plugin-warmup

package:
  patterns:
    - '!infrastructure/**'
