service: greatupsells-storefront-api
frameworkVersion: '^3.38'
useDotenv: true
configValidationMode: error
provider:
  name: aws
  architecture: arm64
  runtime: nodejs20.x
  timeout: 10
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  httpApi:
    shouldStartNameWithService: true
    cors:
      allowedOrigins: '*'
      allowedHeaders:
        - Content-Type
        - shop
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    LOGS_API_URL: ${env:LOGS_API_URL, ssm:/greatupsells/${self:provider.stage}/logs-api/url}
    LOG_QUEUE_URL: ${ssm:/greatupsells/${self:provider.stage}/queues/log/url, ''}
    LOG_SOURCE: 'storefront-api'
    SHOPS_API_URL: ${env:SHOPS_API_URL, ssm:/greatupsells/${self:provider.stage}/shops-api/url}
    SHOPIFY_ADMIN_APP_API_KEY: ${env:SHOPIFY_ADMIN_APP_API_KEY, ssm:/greatupsells/${self:provider.stage}/shopify/api-key}
    SHOPIFY_ADMIN_APP_API_SECRET_KEY: ${env:SHOPIFY_ADMIN_APP_API_SECRET_KEY, ssm:/greatupsells/${self:provider.stage}/shopify/api-secret-key}

custom:
  serverless-offline:
    httpPort: ${env:STOREFRONT_API_PORT, 4006}
    lambdaPort: 4106
    prefix: 'storefront-api'
  customDomain:
    domainName: ${ssm:/greatupsells/${self:provider.stage}/storefront-api/domain, ''}
    basePath: ''
    certificateName: ${ssm:/greatupsells/${self:provider.stage}/certificate-name, ''}
    createRoute53Record: true
    endpointType: regional
    apiType: http
    route53Params:
      routingPolicy: simple
      setIdentifier: ${self:provider.region}
      healthCheckId: ${ssm:/greatupsells/${self:provider.stage}/storefront-api/health-check-id, ''}
    securityPolicy: tls_1_2
    autoDomain: true
  warmupConcurrency:
    test: 1
    production: 5
  warmup:
    default:
      enabled: true
      concurrency: ${self:custom.warmupConcurrency.${opt:stage, self:provider.stage}, 1}
      prewarm: true
      events:
        - schedule: rate(5 minutes)

functions:
  health:
    handler: src/routes/health.handler
    events:
      - httpApi:
          path: /health
          method: get
  region:
    handler: src/routes/region.handler
    events:
      - httpApi:
          path: /region
          method: get
    warmup:
      default:
        enabled: false
  addDraftOrderLineItems:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/addDraftOrderLineItems.handler
    events:
      - httpApi:
          path: /draft-orders/{draftOrderId}/line-items
          method: post
  createDraftOrder:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/createDraftOrder.handler
    events:
      - httpApi:
          path: /draft-orders
          method: post
  findOneRandomOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneRandomOffer.handler
    events:
      - httpApi:
          path: /offers/random
          method: post
  findShop:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShop.handler
    events:
      - httpApi:
          path: /shop
          method: get
  signPostPurchaseChangeset:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/signPostPurchaseChangeset.handler
    events:
      - httpApi:
          path: /post-purchase/changeset-signature
          method: post
  trackOfferAcceptance:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/trackOfferAcceptance.handler
    events:
      - httpApi:
          path: /offers/{offerId}/acceptances
          method: post
  trackOfferImpression:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/trackOfferImpression.handler
    events:
      - httpApi:
          path: /offers/{offerId}/impressions
          method: post
  updateShopifyDraftOrderItems:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updateShopifyDraftOrderItems.handler
    events:
      - httpApi:
          path: /draft-orders/{draftOrderId}/line-items
          method: put

plugins:
  - serverless-offline
  - serverless-plugin-monorepo
  - serverless-domain-manager
  - serverless-plugin-warmup

package:
  patterns:
    - '!infrastructure/**'
    - '!node_modules/**/*.map'
    - '!node_modules/eslint'
