- name: Determine if Elasticsearch is installed
  stat:
    path: /etc/elasticsearch/elasticsearch.yml
  register: elasticsearch

- name: Add Elasticsearch GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: not elasticsearch.stat.exists

- name: Add Elasticsearch sources list
  lineinfile:
    line: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    dest: /etc/apt/sources.list.d/elastic-7.x.list
    state: present
    create: yes
  when: not elasticsearch.stat.exists

- name: Update apt cache
  apt:
    update_cache: yes
  when: not elasticsearch.stat.exists

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes
    cache_valid_time: 3600
    allow_unauthenticated: yes
  when: not elasticsearch.stat.exists

- name: Set Elasticsearch bootstrap password
  command: echo {{ elasticsearch_root_password }} | /usr/share/elasticsearch/bin/elasticsearch-keystore add --stdin "bootstrap.password" -f
  when: not elasticsearch.stat.exists

- name: Generate Elasticsearch certificate
  command: '{{ item }}'
  with_items:
    - /usr/share/elasticsearch/bin/elasticsearch-certutil ca --pem --out /usr/share/elasticsearch/elastic-stack-ca.zip
    - unzip /usr/share/elasticsearch/elastic-stack-ca.zip -d /usr/share/elasticsearch
    - /usr/share/elasticsearch/bin/elasticsearch-certutil cert --ca-cert ca/ca.crt --ca-key ca/ca.key --out /usr/share/elasticsearch/elastic-certificates.p12 --pass ''
    - cp /usr/share/elasticsearch/elastic-certificates.p12 /etc/elasticsearch/
    - chmod 660 /etc/elasticsearch/elastic-certificates.p12
  when: not elasticsearch.stat.exists

- name: Create Elasticsearch config file (test)
  copy:
    src: elasticsearch-test.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0644
  when:
    - not elasticsearch.stat.exists
    - stage == "test"

- name: Create Elasticsearch config file (production, us-east-1)
  copy:
    src: elasticsearch-us-east-1.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0644
  when:
    - not elasticsearch.stat.exists
    - stage == "production"
    - region == "us-east-1"

- name: Create Elasticsearch config file (production, eu-west-1)
  copy:
    src: elasticsearch-eu-west-1.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0644
  when:
    - not elasticsearch.stat.exists
    - stage == "production"
    - region == "eu-west-1"

- name: Create Elasticsearch config file (production, ap-northeast-1)
  copy:
    src: elasticsearch-ap-northeast-1.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0644
  when:
    - not elasticsearch.stat.exists
    - stage == "production"
    - region == "ap-northeast-1"

- name: Ensure Elasticsearch is enabled to start automatically on boot
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
  when: not elasticsearch.stat.exists

- name: Limit Elasticsearch memory usage
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Environment=ES_JAVA_OPTS'
    insertbefore: '^EnvironmentFile='
    line: Environment=ES_JAVA_OPTS="-Xms2g -Xmx2g"

- name: Reload service files
  command: systemctl daemon-reload

- name: Retart Elasticsearch
  service:
    name: elasticsearch
    state: restarted
  when: not elasticsearch.stat.exists

- name: Configure "app" user role for Elasticsearch
  command: |
    curl -k -X POST 'https://elastic:{{ elasticsearch_root_password }}@services.test.greatupsells.com:9200/_security/role/app' -H "Content-Type: application/json" -d '{
      "indices" : [
        {
          "names" : [ "logs*" ],
          "privileges" : [ "all" ]
        }
      ]
    }'

- name: Configure "app" user for Elasticsearch
  command: |
    curl -k -X POST 'https://elastic:{{ elasticsearch_root_password }}@localhost:9200/_security/user/app' -H "Content-Type: application/json" -d '{
      "password" : "{{ elasticsearch_app_password }}",
      "full_name" : "App",
      "roles" : [ "app" ]
    }'

- name: 'TODO: Change Elasticsearch passwords'
  debug:
    msg: 'Run: `/usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive`'
  when: not elasticsearch.stat.exists
