# Reference: https://medium.com/@himanshubhimwal94/a-complete-step-by-step-guide-to-setup-a-3-node-elk-cluster-secured-with-lets-encrypt-b1e988988006

- name: Determine if Elasticsearch is installed
  stat:
    path: /etc/elasticsearch/elasticsearch.yml
  register: elasticsearch

- name: Add Elasticsearch GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: not elasticsearch.stat.exists

- name: Add Elasticsearch sources list
  lineinfile:
    line: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    dest: /etc/apt/sources.list.d/elastic-7.x.list
    state: present
    create: yes
  when: not elasticsearch.stat.exists

- name: Update apt cache
  apt:
    update_cache: yes
  when: not elasticsearch.stat.exists

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes
    cache_valid_time: 3600
    allow_unauthenticated: yes
  when: not elasticsearch.stat.exists

- name: Copy certificates for Elasticsearch
  copy:
    src: /etc/letsencrypt/live/{{ domain }}/
    dest: /etc/elasticsearch/certs/
    remote_src: yes
    local_follow: yes
    owner: root
    group: elasticsearch
    mode: 0644

- name: Set Elasticsearch certs directory permissions
  file:
    path: /etc/elasticsearch/certs
    state: directory
    owner: root
    group: elasticsearch
    mode: 0655

- name: Create Elasticsearch config file (test)
  copy:
    src: elasticsearch-test.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0644
  when:
    - stage == "test"

- name: Create Elasticsearch config file (production, us-east-1)
  copy:
    src: elasticsearch-us-east-1.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0644
  when:
    - stage == "production"
    - region == "us-east-1"

# - name: Create Elasticsearch config file (production, eu-west-1)
#   copy:
#     src: elasticsearch-eu-west-1.yml
#     dest: /etc/elasticsearch/elasticsearch.yml
#     owner: root
#     group: root
#     mode: 0644
#   when:
#     - stage == "production"
#     - region == "eu-west-1"

# - name: Create Elasticsearch config file (production, ap-northeast-1)
#   copy:
#     src: elasticsearch-ap-northeast-1.yml
#     dest: /etc/elasticsearch/elasticsearch.yml
#     owner: root
#     group: root
#     mode: 0644
#   when:
#     - stage == "production"
#     - region == "ap-northeast-1"

- name: Ensure Elasticsearch is enabled to start automatically on boot
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
  when: not elasticsearch.stat.exists

- name: Limit Elasticsearch memory usage
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/elasticsearch.service
    regexp: '^Environment=ES_JAVA_OPTS'
    insertbefore: '^EnvironmentFile='
    line: Environment=ES_JAVA_OPTS="-Xms1g -Xmx1g"
  when:
    - stage == "test"

- name: Limit Elasticsearch memory usage
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/elasticsearch.service
    regexp: '^Environment=ES_JAVA_OPTS'
    insertbefore: '^EnvironmentFile='
    line: Environment=ES_JAVA_OPTS="-Xms2g -Xmx2g"
  when:
    - stage == "production"

- name: Reload service files
  command: systemctl daemon-reload

- name: Restart Elasticsearch
  service:
    name: elasticsearch
    state: restarted
  when: not elasticsearch.stat.exists

- name: 'TODO: Change Elasticsearch passwords'
  debug:
    msg: 'Run: `/usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive`'
  when: not elasticsearch.stat.exists

- name: 'TODO: Configure "app" user role for Elasticsearch'
  debug:
    msg: |
      curl -k -X POST 'https://elastic:{{ elasticsearch_root_password }}@{{ services_domain }}:9200/_security/role/app' -H "Content-Type: application/json" -d '{
        "cluster": ["monitor"],
        "indices" : [
          {
            "names" : [ "logs" ],
            "privileges" : [ "all" ]
          }
        ]
      }'
  when: not elasticsearch.stat.exists

- name: 'TODO: Configure "app" user for Elasticsearch'
  debug:
    msg: |
      curl -k -X POST 'https://elastic:{{ elasticsearch_root_password }}@{{ services_domain }}:9200/_security/user/app' -H "Content-Type: application/json" -d '{
        "password" : "{{ elasticsearch_app_password }}",
        "full_name" : "App",
        "roles" : [ "app" ]
      }'
  when: not elasticsearch.stat.exists
