name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - chad
body:
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: List necessary steps to reproduce the issue.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you see happen?
      placeholder: Describe what happened.
    validations:
      required: true
  - type: textarea
    id: what-should-have-happened
    attributes:
      label: What should have happened?
      description: What did you expect to happen?
      placeholder: Describe what should have happened.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari for MacOS
        - Safari for iOS
        - Microsoft Edge
  - type: textarea
    id: notes
    attributes:
      label: Additional notes
      description: Please provide any other relevant notes.
      placeholder: Notes
