service: greatupsells-email-service
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 10
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    shouldStartNameWithService: true
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}

custom:
  customDomain:
    domainName: ${ssm:/greatupsells/${self:provider.stage}/email-api/regional-domain, ''}
    basePath: ''
    certificateName: ${ssm:/greatupsells/${self:provider.stage}/certificate-name, ''}
    createRoute53Record: true
    endpointType: regional
    securityPolicy: tls_1_2
    autoDomain: true

functions:
  health:
    memorySize: 128
    handler: src/routes/health.handler
    events:
      - http:
          path: /health
          method: get
          cors: true
  sending:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    memorySize: 256
    reservedConcurrency: 1
    handler: src/workers/sending.handler
    events:
      - sqs:
          arn: ${ssm:/greatupsells/${self:provider.stage}/queues/email-sending/arn, 'arn:aws:sqs:${self:provider.region}:000000000000:email-sending-queue-dev'}
          batchSize: 1

plugins:
  - serverless-plugin-monorepo
  - serverless-domain-manager

package:
  patterns:
    - '!infrastructure/**'
