const logger = require('@greatupsells/logger');

const { APP_NAME_SLUG, SHOPIFY_EMBED_BLOCK_ID } = process.env;

const checkIfInstalled = (settingsData) => {
  const settingsDataBlocks = Object.values(settingsData.current.blocks || {});
  const appEmbedBlockTypePrefix = `shopify://apps/${APP_NAME_SLUG}/blocks/app-embed`;
  const appEmbedBlock = settingsDataBlocks.find((block) =>
    block.type.includes(appEmbedBlockTypePrefix)
  );
  const appEmbedBlockIsInstalled = !!appEmbedBlock;

  return appEmbedBlockIsInstalled;
};

const install = async (shop, shopifyThemeId, settingsData) => {
  const shopifyApiClient = shop.getShopifyApiClient();

  // This is just a reused random ID generated by Shopify during development.
  const blockId = '5338002829674597862';

  // Add the block to the theme settings.
  settingsData.current = settingsData.current || {};
  settingsData.current.blocks = settingsData.current.blocks || {};
  settingsData.current.blocks[blockId] = {
    type: `shopify:\/\/apps/${APP_NAME_SLUG}\/blocks\/app-embed\/${SHOPIFY_EMBED_BLOCK_ID}`,
    disabled: false,
    settings: {}
  };

  await shopifyApiClient.asset.update(shopifyThemeId, {
    key: 'config/settings_data.json',
    value: JSON.stringify(settingsData)
  });
};

const installAppEmbedBlock = async (shop, shopifyThemeId) => {
  const shopifyApiClient = shop.getShopifyApiClient();

  // Get asset settings file.
  const settingsData = await shopifyApiClient.asset.get(shopifyThemeId, {
    'asset[key]': 'config/settings_data.json'
  });
  const settingsDataJson = JSON.parse(settingsData.value);

  // Check if app embed block is installed in theme.
  const appEmbedBlockIsInstalled = checkIfInstalled(settingsDataJson);

  // Install app block if not installed.
  if (!appEmbedBlockIsInstalled) {
    await install(shop, shopifyThemeId, settingsDataJson);
    await logger.info(
      `Installed app embed block for shop (${shop.toString()})`,
      { settingsData }
    );
  }
};

module.exports = installAppEmbedBlock;
