service: greatupsells-shopify-admin-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 2048
  timeout: 10
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    shouldStartNameWithService: true
  httpApi:
    cors: true
    authorizers:
      authorizer:
        type: request
        functionName: authorizer
        identitySource: $request.header.Authorization
        resultTtlInSeconds: 0
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    JWT_SECRET: ${env:JWT_SECRET, ssm:/greatupsells/${self:provider.stage}/jwt-secret}
    LOGS_API_URL: ${env:LOGS_API_URL, ssm:/greatupsells/${self:provider.stage}/logs-api/url}
    LOG_QUEUE_URL: ${ssm:/greatupsells/${self:provider.stage}/queues/log/url, ''}
    LOG_SOURCE: 'shopify-admin-api'
    SHOPS_API_URL: ${env:SHOPS_API_URL, ssm:/greatupsells/${self:provider.stage}/shops-api/url}

custom:
  serverless-offline:
    httpPort: ${env:SHOPIFY_ADMIN_API_PORT, 4000}
    lambdaPort: 4100
  customDomain:
    domainName: ${ssm:/greatupsells/${self:provider.stage}/shopify-admin-api/domain, ''}
    basePath: ''
    certificateName: ${ssm:/greatupsells/${self:provider.stage}/certificate-name, ''}
    createRoute53Record: true
    endpointType: regional
    route53Params:
      routingPolicy: latency
      setIdentifier: ${self:provider.region}
      healthCheckId: ${ssm:/greatupsells/${self:provider.stage}/shopify-admin-api/health-check-id, ''}
    securityPolicy: tls_1_2
    autoDomain: true
  warmup:
    default:
      enabled: true
      memorySize: 128
      concurrency: 5
      prewarm: true
      events:
        - schedule: rate(5 minutes)

functions:
  authorizer:
    handler: src/authorizer.handler
  health:
    memorySize: 128
    handler: src/routes/health.handler
    events:
      - httpApi:
          path: /health
          method: get
  region:
    memorySize: 128
    handler: src/routes/region.handler
    events:
      - httpApi:
          path: /region
          method: get
    warmup:
      default:
        enabled: false
  activatePlan:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/activatePlan.handler
    events:
      - httpApi:
          path: /plan/activation
          method: post
          authorizer:
            name: authorizer
  changePlan:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/changePlan.handler
    events:
      - httpApi:
          path: /plan
          method: post
          authorizer:
            name: authorizer
  cloneOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/cloneOffer.handler
    events:
      - httpApi:
          path: /offers/{offerId}/clone
          method: post
          authorizer:
            name: authorizer
  consentToDataAccess:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/consentToDataAccess.handler
    events:
      - httpApi:
          path: /shop/data-access-consent
          method: post
          authorizer:
            name: authorizer
  createOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/createOffer.handler
    events:
      - httpApi:
          path: /offers
          method: post
          authorizer:
            name: authorizer
  createTheme:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/createTheme.handler
    events:
      - httpApi:
          path: /themes
          method: post
          authorizer:
            name: authorizer
  deleteOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/deleteOffer.handler
    events:
      - httpApi:
          path: /offers/{offerId}
          method: delete
          authorizer:
            name: authorizer
  findOneOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneOffer.handler
    events:
      - httpApi:
          path: /offers/{offerId}
          method: get
          authorizer:
            name: authorizer
  findOfferAcceptances:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferAcceptances.handler
    events:
      - httpApi:
          path: /offers/{offerId}/acceptances
          method: get
          authorizer:
            name: authorizer
  findOfferConversionRates:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferConversionRates.handler
    events:
      - httpApi:
          path: /offers/{offerId}/conversion-rates
          method: get
          authorizer:
            name: authorizer
  findOfferConversions:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferConversions.handler
    events:
      - httpApi:
          path: /offers/{offerId}/conversions
          method: get
          authorizer:
            name: authorizer
  findOfferThemes:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferThemes.handler
    events:
      - httpApi:
          path: /offers/{offerId}/themes
          method: get
          authorizer:
            name: authorizer
  findOfferRevenueIncreases:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferRevenueIncreases.handler
    events:
      - httpApi:
          path: /offers/{offerId}/revenue-increases
          method: get
          authorizer:
            name: authorizer
  findOffers:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOffers.handler
    events:
      - httpApi:
          path: /offers
          method: get
          authorizer:
            name: authorizer
  findOfferImpressions:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferImpressions.handler
    events:
      - httpApi:
          path: /offers/{offerId}/impressions
          method: get
          authorizer:
            name: authorizer
  findOneRandomCollection:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneRandomCollection.handler
    events:
      - httpApi:
          path: /collections/random
          method: get
          authorizer:
            name: authorizer
  findOneRandomProduct:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneRandomProduct.handler
    events:
      - httpApi:
          path: /products/random
          method: get
          authorizer:
            name: authorizer
  findShop:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShop.handler
    events:
      - httpApi:
          path: /shop
          method: get
          authorizer:
            name: authorizer
  findThemes:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findThemes.handler
    events:
      - httpApi:
          path: /themes
          method: get
          authorizer:
            name: authorizer
  findShopAcceptances:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopAcceptances.handler
    events:
      - httpApi:
          path: /shop/acceptances
          method: get
          authorizer:
            name: authorizer
  findShopConversionRates:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopConversionRates.handler
    events:
      - httpApi:
          path: /shop/conversion-rates
          method: get
          authorizer:
            name: authorizer
  findShopConversions:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopConversions.handler
    events:
      - httpApi:
          path: /shop/conversions
          method: get
          authorizer:
            name: authorizer
  findShopImpressions:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopImpressions.handler
    events:
      - httpApi:
          path: /shop/impressions
          method: get
          authorizer:
            name: authorizer
  findShopRevenueIncreases:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopRevenueIncreases.handler
    events:
      - httpApi:
          path: /shop/revenue-increases
          method: get
          authorizer:
            name: authorizer
  updateOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updateOffer.handler
    events:
      - httpApi:
          path: /offers/{offerId}
          method: put
          authorizer:
            name: authorizer
  updateTheme:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updateTheme.handler
    events:
      - httpApi:
          path: /themes/{themeId}
          method: put
          authorizer:
            name: authorizer

plugins:
  - serverless-offline
  - serverless-plugin-monorepo
  - serverless-domain-manager
  - serverless-plugin-warmup

package:
  patterns:
    - '!infrastructure/**'
    - '!node_modules/**/*.map'
    - '!node_modules/**/aws-sdk'
    - '!node_modules/aws-sdk'
    - '!node_modules/eslint'
