service: upselling-shopify-admin-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 10
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    shouldStartNameWithService: true
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    JWT_SECRET: ${env:JWT_SECRET, ssm:/upselling/${self:provider.stage}/jwt-secret~true}
    LOGS_API_URL: ${env:LOGS_API_URL, ssm:/upselling/${self:provider.stage}/logs-api/url}
    LOG_QUEUE_URL: ${env:LOG_QUEUE_URL, ssm:/upselling/${self:provider.stage}/queues/log/url}
    LOG_SOURCE: 'shopify-admin-api'
    SHOPS_API_URL: ${env:SHOPS_API_URL, ssm:/upselling/${self:provider.stage}/shops-api/url}

custom:
  serverless-offline:
    httpPort: ${env:SHOPIFY_ADMIN_API_PORT, 4000}
    lambdaPort: 5000
  customDomain:
    domainName: ${env:SHOPIFY_ADMIN_API_SERVICE_DOMAIN, ssm:/upselling/${self:provider.stage}/shopify-admin-api/domain}
    basePath: ''
    certificateName: ${env:CERTIFICATE_NAME, ssm:/upselling/${self:provider.stage}/certificate-name}
    createRoute53Record: true
    endpointType: regional
    route53Params:
      routingPolicy: latency
      setIdentifier: ${self:provider.region}
      healthCheckId: ${ssm:/upselling/${self:provider.stage}/shopify-admin-api/health-check-id}
    securityPolicy: tls_1_2
    autoDomain: true
  warmup:
    default:
      enabled: true
      concurrency: 5
      prewarm: true
      events:
        - schedule: rate(5 minutes)

functions:
  authorizer:
    handler: src/authorizer.handler
  health:
    memorySize: 128
    handler: src/routes/health.handler
    events:
      - http:
          path: /health
          method: get
          cors: true
    warmup:
      default:
        enabled: false
  region:
    memorySize: 128
    handler: src/routes/region.handler
    events:
      - http:
          path: /region
          method: get
          cors: true
    warmup:
      default:
        enabled: false
  cloneOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/cloneOffer.handler
    events:
      - http:
          path: /offers/{offerId}/clone
          method: post
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  createOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/createOffer.handler
    events:
      - http:
          path: /offers
          method: post
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  createPopupTheme:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/createPopupTheme.handler
    events:
      - http:
          path: /popup-themes
          method: post
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  deleteOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/deleteOffer.handler
    events:
      - http:
          path: /offers/{offerId}
          method: delete
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findOneOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOneOffer.handler
    events:
      - http:
          path: /offers/{offerId}
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findOfferAcceptances:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferAcceptances.handler
    events:
      - http:
          path: /offers/{offerId}/acceptances
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findOfferConversionRates:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferConversionRates.handler
    events:
      - http:
          path: /offers/{offerId}/conversion-rates
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findOfferConversions:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferConversions.handler
    events:
      - http:
          path: /offers/{offerId}/conversions
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findOfferPopupThemes:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferPopupThemes.handler
    events:
      - http:
          path: /offers/{offerId}/popup-themes
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findOfferRevenueIncreases:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferRevenueIncreases.handler
    events:
      - http:
          path: /offers/{offerId}/revenue-increases
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findOffers:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOffers.handler
    events:
      - http:
          path: /offers
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findOfferImpressions:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOfferImpressions.handler
    events:
      - http:
          path: /offers/{offerId}/impressions
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findShop:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShop.handler
    events:
      - http:
          path: /shop
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findPopupThemes:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findPopupThemes.handler
    events:
      - http:
          path: /popup-themes
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findShopAcceptances:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopAcceptances.handler
    events:
      - http:
          path: /shop/acceptances
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findShopConversionRates:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopConversionRates.handler
    events:
      - http:
          path: /shop/conversion-rates
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findShopConversions:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopConversions.handler
    events:
      - http:
          path: /shop/conversions
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findShopImpressions:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopImpressions.handler
    events:
      - http:
          path: /shop/impressions
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  findShopRevenueIncreases:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findShopRevenueIncreases.handler
    events:
      - http:
          path: /shop/revenue-increases
          method: get
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  updateOffer:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updateOffer.handler
    events:
      - http:
          path: /offers/{offerId}
          method: put
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  updatePopupTheme:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updatePopupTheme.handler
    events:
      - http:
          path: /popup-themes/{popupThemeId}
          method: put
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
  updateShop:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updateShop.handler
    events:
      - http:
          path: /shop
          method: put
          cors: true
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0

plugins:
  - serverless-offline
  - serverless-plugin-monorepo
  - serverless-domain-manager
  - serverless-plugin-warmup

package:
  exclude:
    - infrastructure/**
