- name: Wait for the server to be reachable
  wait_for_connection:
    timeout: 900

- name: Gather facts
  setup:

- name: Update all packages
  apt:
    upgrade: dist

- name: Prevent unattended upgrades
  apt:
    pkg: unattended-upgrades
    state: absent

- name: Check if swap file exists
  command: file /swapfile
  register: swapfile

- name: Create swap file
  command: fallocate -l 4G /swapfile
  when: swapfile.stdout.find('swap file') == -1

- name: Set swap file permissions
  file:
    path: /swapfile
    owner: root
    group: root
    mode: 0600
  when: swapfile.stdout.find('swap file') == -1

- name: Set up swap area
  command: mkswap /swapfile
  when: swapfile.stdout.find('swap file') == -1

- name: Add swap entry in fstab
  mount:
    name: none
    src: /swapfile
    fstype: swap
    opts: sw
    passno: '0'
    dump: '0'
    state: present
  when: swapfile.stdout.find('swap file') == -1

- name: Mount swap
  command: swapon /swapfile
  when: swapfile.stdout.find('swap file') == -1

- name: Set vm.swappiness
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present

- name: Install packages
  apt:
    pkg:
      - software-properties-common
      - ntp
      - python3
      - python3-pip
      - jq
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Install AWS CLI
  raw: pip3 install -q awscli --upgrade

- name: Install Python packages
  raw: pip3 install -q pymongo --upgrade

- name: Create AWS config directory
  file:
    path: /root/.aws
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Configure AWS CLI credentials
  vars:
    content: |
      [default]
      aws_access_key_id = {{ aws_access_key_id }}
      aws_secret_access_key = {{ aws_secret_access_key }}
  copy:
    content: '{{ content }}'
    dest: /root/.aws/credentials

- name: Configure AWS CLI settings
  vars:
    content: |
      [default]
      region = us-east-1
  copy:
    content: '{{ content }}'
    dest: /root/.aws/config

- name: Set Cron PATH
  cronvar:
    name: PATH
    value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

- name: Install Let's Encrypt and Certbot
  apt:
    pkg:
      - letsencrypt
      - python3-certbot-dns-route53
    state: present
    update_cache: yes
    cache_valid_time: 3600
    allow_unauthenticated: yes

- name: Determine if certificates exist
  stat:
    path: '/etc/letsencrypt/live/{{ domain_name }}'
  register: certificates

- name: Obtain SSL certificate
  command: 'certbot certonly --non-interactive --agree-tos --preferred-challenges dns --dns-route53 -m greatupsells@neatowebsolutions.com -d {{ domain_name }}'
  when: certificates.stat.isdir is not defined

- name: Install Let's Encrypt Certificate Authority Root Certificate
  copy:
    src: ca.crt
    dest: /etc/ssl/ca.crt
    owner: root
    group: root
    mode: 0644

- name: Create certificate update script
  copy:
    src: update-certificates.sh
    dest: /root/update-certificates.sh
    owner: root
    group: root
    mode: 0744

- name: Inject domain into certificate update script
  replace:
    path: /root/update-certificates.sh
    regexp: "\/domain_name\/"
    replace: "\/{{ domain_name }}\/"

- name: Set up a job for updating certificate
  cron:
    name: update-certificates
    minute: '0'
    hour: '0,12'
    user: root
    job: 'certbot renew --renew-hook /root/update-certificates.sh >> /root/certbot-cron.log 2>&1'

- name: Generate certificate files
  command: /root/update-certificates.sh
