service: upselling-admin-api-gateway
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 10
  endpointType: REGIONAL
  stage: ${env:STAGE, 'dev'}
  region: ${env:AWS_REGION, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    shouldStartNameWithService: true
  environment:
    JWT_SECRET: ${env:JWT_SECRET, ssm:/upselling/${self:provider.stage}/jwt-secret~true}
    LOG_QUEUE_URL: ${env:LOG_QUEUE_URL, ssm:/upselling/${self:provider.stage}/queues/log/url}
    LOG_SOURCE: 'admin-api-gateway'
    SHOPS_API_URL: ${env:SHOPS_API_URL, ssm:/upselling/${self:provider.stage}/shops-api/url}

functions:
  # authorizer:
  #   handler: src/authorizer.handler
  # health:
  #   handler: src/routes/health.handler
  #   events:
  #     - http:
  #         path: /health
  #         method: get
  #         cors: true
  # region:
  #   handler: src/routes/region.handler
  #   events:
  #     - http:
  #         path: /region
  #         method: get
  #         cors: true
  # findLogs:
  createPopupTheme:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/createPopupTheme.handler
    events:
      - http:
          path: /popup-themes
          method: post
          cors: true
          # authorizer:
          #   name: authorizer
          #   type: request
          #   identitySource: method.request.header.Authorization
  findOnePopupTheme:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findOnePopupTheme.handler
    events:
      - http:
          path: /popup-themes/{popupThemeId}
          method: get
          cors: true
          # authorizer:
          #   name: authorizer
          #   type: request
          #   identitySource: method.request.header.Authorization
  findPopupThemes:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findPopupThemes.handler
    events:
      - http:
          path: /popup-themes
          method: get
          cors: true
          # authorizer:
          #   name: authorizer
          #   type: request
          #   identitySource: method.request.header.Authorization
  # findShops:
  # findStats:
  updatePopupTheme:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/updatePopupTheme.handler
    events:
      - http:
          path: /popup-themes/{popupThemeId}
          method: put
          cors: true
          # authorizer:
          #   name: authorizer
          #   type: request
          #   identitySource: method.request.header.Authorization
plugins:
  - serverless-offline
  - serverless-plugin-monorepo
  - serverless-domain-manager

custom:
  serverless-offline:
    httpPort: ${env:ADMIN_API_GATEWAY_PORT}
    lambdaPort: 5003
  customDomain:
    domainName: ${env:ADMIN_API_GATEWAY_SERVICE_ENDPOINT, ssm:/upselling/${self:provider.stage}/admin-api-gateway/endpoint/${self:provider.region}}
    basePath: ''
    certificateName: ${env:CERTIFICATE_NAME, ssm:/upselling/${self:provider.stage}/certificate-name}
    createRoute53Record: true
    endpointType: regional
    securityPolicy: tls_1_2

package:
  exclude:
    - test/**
    - node_modules/aws-sdk
    - node_modules/**/aws-sdk
    - node_modules/**/*.map
