variable "domain_hosted_zone_id" {}
variable "certificate_name" {}
variable "acm_certificate_arn" {}
variable "cdn_price_class" {}
variable "mongodb_database" {}
variable "mongodb_app_user" {}
variable "shopify_admin_name" {}
variable "shopify_admin_url" {}
variable "shopify_admin_domain" {}
variable "shopify_admin_endpoint" {}
variable "shopify_admin_endpoint_us" {}
variable "shopify_admin_endpoint_asia" {}
variable "shopify_admin_endpoint_europe" {}
variable "shopify_admin_api_key" {}
variable "shopify_admin_static_domain" {}
variable "shopify_admin_bucket_name_us" {}
variable "shopify_admin_bucket_name_asia" {}
variable "shopify_admin_bucket_name_europe" {}
variable "api_url" {}
variable "api_domain" {}
variable "api_us_endpoint" {}
variable "api_asia_endpoint" {}
variable "api_europe_endpoint" {}
variable "admin_app_domain" {}
variable "admin_app_endpoint" {}
variable "admin_app_bucket_name" {}
variable "contact_email" {}
variable "sandbox" {}
