service: greatupsells-webhooks-service
frameworkVersion: '^3.38'
useDotenv: true
configValidationMode: error
provider:
  name: aws
  architecture: arm64
  runtime: nodejs20.x
  memorySize: 256
  timeout: 10
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  httpApi:
    shouldStartNameWithService: true
    cors: true
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    LOGS_API_URL: ${env:LOGS_API_URL, ssm:/greatupsells/${self:provider.stage}/logs-api/url}
    LOG_QUEUE_URL: ${ssm:/greatupsells/${self:provider.stage}/queues/log/url, ''}
    LOG_SOURCE: 'webhooks-service'
    SHOPIFY_ADMIN_APP_API_SECRET_KEY: ${env:SHOPIFY_ADMIN_APP_API_SECRET_KEY, ssm:/greatupsells/${self:provider.stage}/shopify/api-secret-key}
    SHOPS_API_URL: ${env:SHOPS_API_URL, ssm:/greatupsells/${self:provider.stage}/shops-api/url}

custom:
  serverless-offline:
    httpPort: ${env:WEBHOOK_PORT, 4008}
    lambdaPort: 4108
    prefix: 'webhooks-api'
  customDomain:
    domainName: ${ssm:/greatupsells/${self:provider.stage}/webhooks-service/regional-domain, ''}
    basePath: ''
    certificateName: ${ssm:/greatupsells/${self:provider.stage}/certificate-name, ''}
    createRoute53Record: true
    endpointType: regional
    apiType: http
    route53Params:
      healthCheckId: ${ssm:/greatupsells/${self:provider.stage}/webhooks-service/health-check-id, ''}
    securityPolicy: tls_1_2
    autoDomain: true
  warmup:
    default:
      enabled: true
      concurrency: 1
      prewarm: true
      events:
        - schedule: rate(5 minutes)

functions:
  health:
    handler: src/routes/health.handler
    events:
      - httpApi:
          path: /health
          method: get
    warmup:
      default:
        enabled: false
  appUninstall:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/appUninstall.handler
    events:
      - sqs:
          arn: ${ssm:/greatupsells/${self:provider.stage}/queues/app-uninstall/arn, 'arn:aws:sqs:${self:provider.region}:000000000000:app-uninstall-queue-dev'}
      - httpApi:
          path: /shopify/app-uninstall
          method: post
  collection:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/collection.handler
    events:
      - sqs:
          arn: ${ssm:/greatupsells/${self:provider.stage}/queues/collection/arn, 'arn:aws:sqs:${self:provider.region}:000000000000:collection-queue-dev'}
      - httpApi:
          path: /shopify/collection
          method: post
  collectionDelete:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/collectionDelete.handler
    events:
      - sqs:
          arn: ${ssm:/greatupsells/${self:provider.stage}/queues/collection-deletion/arn, 'arn:aws:sqs:${self:provider.region}:000000000000:collection-deletion-queue-dev'}
      - httpApi:
          path: /shopify/collection-deletion
          method: post
  draftOrderUpdate:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/draftOrderUpdate.handler
    events:
      - sqs:
          arn: ${ssm:/greatupsells/${self:provider.stage}/queues/draft-order-update/arn, 'arn:aws:sqs:${self:provider.region}:000000000000:draft-order-update-queue-dev'}
      - httpApi:
          path: /shopify/draft-order-update
          method: post
  orderCancel:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/orderCancel.handler
    events:
      - sqs:
          arn: ${ssm:/greatupsells/${self:provider.stage}/queues/order-cancelation/arn, 'arn:aws:sqs:${self:provider.region}:000000000000:order-cancelation-queue-dev'}
      - httpApi:
          path: /shopify/order-cancelation
          method: post
  orderCreate:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/orderCreate.handler
    events:
      - sqs:
          arn: ${ssm:/greatupsells/${self:provider.stage}/queues/order-create/arn, 'arn:aws:sqs:${self:provider.region}:000000000000:order-create-queue-dev'}
      - httpApi:
          path: /shopify/order-create
          method: post
  orderPaid:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/orderPaid.handler
    events:
      - sqs:
          arn: ${ssm:/greatupsells/${self:provider.stage}/queues/order-paid/arn, 'arn:aws:sqs:${self:provider.region}:000000000000:order-paid-queue-dev'}
      - httpApi:
          path: /shopify/order-paid
          method: post
  orderUpdate:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/orderUpdate.handler
    events:
      - sqs:
          arn: ${ssm:/greatupsells/${self:provider.stage}/queues/order-update/arn, 'arn:aws:sqs:${self:provider.region}:000000000000:order-update-queue-dev'}
      - httpApi:
          path: /shopify/order-update
          method: post
  product:
    reservedConcurrency: 3
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/product.handler
    events:
      - sqs:
          arn: ${ssm:/greatupsells/${self:provider.stage}/queues/product/arn, 'arn:aws:sqs:${self:provider.region}:000000000000:product-queue-dev'}
          batchSize: 10
          maximumBatchingWindow: 10
      - httpApi:
          path: /shopify/product
          method: post
  productDelete:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/productDelete.handler
    events:
      - sqs:
          arn: ${ssm:/greatupsells/${self:provider.stage}/queues/product-deletion/arn, 'arn:aws:sqs:${self:provider.region}:000000000000:product-deletion-queue-dev'}
      - httpApi:
          path: /shopify/product-deletion
          method: post
  shop:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/shop.handler
    events:
      - sqs:
          arn: ${ssm:/greatupsells/${self:provider.stage}/queues/shop-update/arn, 'arn:aws:sqs:${self:provider.region}:000000000000:shop-update-queue-dev'}
      - httpApi:
          path: /shopify/shop
          method: post
  themePublish:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/themePublish.handler
    events:
      - sqs:
          arn: ${ssm:/greatupsells/${self:provider.stage}/queues/theme-publish/arn, 'arn:aws:sqs:${self:provider.region}:000000000000:theme-publish-queue-dev'}
      - httpApi:
          path: /shopify/theme-publish
          method: post
  customerDataRequest:
    handler: src/workers/customerDataRequest.handler
    events:
      - http:
          path: webhooks/customers/data-request
          method: post
          cors: true
  customerRedact:
    handler: src/workers/customerRedact.handler
    events:
      - http:
          path: webhooks/customers/redact
          method: post
          cors: true
  shopRedact:
    handler: src/workers/shopRedact.handler
    events:
      - http:
          path: webhooks/shop/redact
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-monorepo
  - serverless-domain-manager
  - serverless-plugin-warmup

package:
  patterns:
    - '!infrastructure/**'
