service: upselling-webhooks-service

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 10
  endpointType: REGIONAL
  stage: ${env:STAGE, 'dev'}
  region: ${env:AWS_REGION, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    shouldStartNameWithService: true
  environment:
    LOG_QUEUE_URL: ${env:LOG_QUEUE_URL, ssm:/upselling/${self:provider.stage}/queues/log/url}
    LOG_SOURCE: 'webhooks-service'
    SHOPIFY_ADMIN_APP_API_SECRET_KEY: ${env:SHOPIFY_ADMIN_APP_API_SECRET_KEY, ssm:/upselling/${self:provider.stage}/shopify-admin/api-secret-key~true}
    SHOPS_API_URL: ${env:SHOPS_API_URL, ssm:/upselling/${self:provider.stage}/shops-api/url}

functions:
  health:
    handler: src/routes/health.handler
    events:
      - http:
          path: /health
          method: get
          cors: true
  appUninstall:
    reservedConcurrency: 1
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/appUninstall.handler
    events:
      - sqs:
          arn: ${ssm:/upselling/${self:provider.stage}/queues/app-uninstall/arn}
  collection:
    reservedConcurrency: 1
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/collection.handler
    events:
      - sqs:
          arn: ${ssm:/upselling/${self:provider.stage}/queues/collection/arn}
  collectionDeletion:
    reservedConcurrency: 1
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/collectionDeletion.handler
    events:
      - sqs:
          arn: ${ssm:/upselling/${self:provider.stage}/queues/collection-deletion/arn}
  orderCancelation:
    reservedConcurrency: 1
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/orderCancelation.handler
    events:
      - sqs:
          arn: ${ssm:/upselling/${self:provider.stage}/queues/order-cancelation/arn}
  orderPaid:
    reservedConcurrency: 1
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/orderPaid.handler
    events:
      - sqs:
          arn: ${ssm:/upselling/${self:provider.stage}/queues/order-paid/arn}
  orderUpdate:
    reservedConcurrency: 1
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/orderUpdate.handler
    events:
      - sqs:
          arn: ${ssm:/upselling/${self:provider.stage}/queues/order-update/arn}
  product:
    reservedConcurrency: 2
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/product.handler
    events:
      - sqs:
          arn: ${ssm:/upselling/${self:provider.stage}/queues/product/arn}
          batchSize: 10
          maximumBatchingWindow: 60
  productDeletion:
    reservedConcurrency: 1
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/productDeletion.handler
    events:
      - sqs:
          arn: ${ssm:/upselling/${self:provider.stage}/queues/product-deletion/arn}
  shop:
    reservedConcurrency: 1
    role: ${ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/shop.handler
    events:
      - sqs:
          arn: ${ssm:/upselling/${self:provider.stage}/queues/shop-update/arn}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-monorepo

custom:
  dotenv:
    path: .env
  customDomain:
    domainName: ${ssm:/upselling/${self:provider.stage}/webhooks/endpoint/${self:provider.region}}
    basePath: ''
    certificateName: ${ssm:/upselling/${self:provider.stage}/certificate-name}
    createRoute53Record: true
    endpointType: regional
    securityPolicy: tls_1_2

package:
  exclude:
    - test/**
    - node_modules/aws-sdk
    - node_modules/**/aws-sdk
    - node_modules/**/*.map
