service: upselling-webhooks-service
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  timeout: 10
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    shouldStartNameWithService: true
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    LOGS_API_URL: ${env:LOGS_API_URL, ssm:/upselling/${self:provider.stage}/logs-api/url}
    LOG_QUEUE_URL: ${env:LOG_QUEUE_URL, ssm:/upselling/${self:provider.stage}/queues/log/url}
    LOG_SOURCE: 'webhooks-service'
    SHOPIFY_ADMIN_APP_API_SECRET_KEY: ${env:SHOPIFY_ADMIN_APP_API_SECRET_KEY, ssm:/upselling/${self:provider.stage}/shopify/api-secret-key~true}
    SHOPS_API_URL: ${env:SHOPS_API_URL, ssm:/upselling/${self:provider.stage}/shops-api/url}

custom:
  serverless-offline:
    httpPort: ${env:WEBHOOK_PORT, 4008}
    lambdaPort: 5004
  warmup:
    default:
      enabled: true
      concurrency: 5
      prewarm: true
      events:
        - schedule: rate(5 minutes)

functions:
  health:
    handler: src/routes/health.handler
    events:
      - http:
          path: /health
          method: get
          cors: true
    warmup:
      default:
        enabled: true
  appUninstall:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/appUninstall.handler
    events:
      - sqs:
          arn: ${env:APP_UNINSTALL_QUEUE_ARN, ssm:/upselling/${self:provider.stage}/queues/app-uninstall/arn}
      - http:
          path: /shopify/app-uninstall
          method: post
    warmup:
      default:
        enabled: true
  collection:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/collection.handler
    events:
      - sqs:
          arn: ${env:COLLECTION_QUEUE_ARN, ssm:/upselling/${self:provider.stage}/queues/collection/arn}
      - http:
          path: /shopify/collection
          method: post
    warmup:
      default:
        enabled: true
  collectionDelete:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/collectionDelete.handler
    events:
      - sqs:
          arn: ${env:COLLECTION_DELETION_QUEUE_ARN, ssm:/upselling/${self:provider.stage}/queues/collection-deletion/arn}
      - http:
          path: /shopify/collection-deletion
          method: post
    warmup:
      default:
        enabled: true
  orderCancel:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/orderCancel.handler
    events:
      - sqs:
          arn: ${env:ORDER_CANCELATION_QUEUE_ARN, ssm:/upselling/${self:provider.stage}/queues/order-cancelation/arn}
      - http:
          path: /shopify/order-cancelation
          method: post
    warmup:
      default:
        enabled: true
  orderPaid:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/orderPaid.handler
    events:
      - sqs:
          arn: ${env:ORDER_PAID_QUEUE_ARN, ssm:/upselling/${self:provider.stage}/queues/order-paid/arn}
      - http:
          path: /shopify/order-paid
          method: post
    warmup:
      default:
        enabled: true
  orderUpdate:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/orderUpdate.handler
    events:
      - sqs:
          arn: ${env:ORDER_UPDATE_QUEUE_ARN, ssm:/upselling/${self:provider.stage}/queues/order-update/arn}
      - http:
          path: /shopify/order-update
          method: post
    warmup:
      default:
        enabled: true
  product:
    reservedConcurrency: 2
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/product.handler
    events:
      - sqs:
          arn: ${env:PRODUCT_QUEUE_ARN, ssm:/upselling/${self:provider.stage}/queues/product/arn}
          batchSize: 10
          maximumBatchingWindow: 10
      - http:
          path: /shopify/product
          method: post
    warmup:
      default:
        enabled: true
  productDelete:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/productDelete.handler
    events:
      - sqs:
          arn: ${env:PRODUCT_DELETION_QUEUE_ARN, ssm:/upselling/${self:provider.stage}/queues/product-deletion/arn}
      - http:
          path: /shopify/product-deletion
          method: post
    warmup:
      default:
        enabled: true
  shop:
    reservedConcurrency: 1
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/workers/shop.handler
    events:
      - sqs:
          arn: ${env:SHOP_QUEUE_ARN, ssm:/upselling/${self:provider.stage}/queues/shop-update/arn}
      - http:
          path: /shopify/shop
          method: post
    warmup:
      default:
        enabled: true

plugins:
  - serverless-offline
  - serverless-plugin-monorepo
  - serverless-plugin-warmup

package:
  exclude:
    - infrastructure/**
