service: greatupsells-admin-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 2048
  timeout: 10
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  httpApi:
    shouldStartNameWithService: true
    disableDefaultEndpoint: true
    cors: true
    # authorizers:
    #   authorizer:
    #     type: request
    #     functionName: authorizer
    #     identitySource: $request.header.Authorization
    #     resultTtlInSeconds: 0
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    JWT_SECRET: ${env:JWT_SECRET, ssm:/greatupsells/${self:provider.stage}/jwt-secret}
    LOGS_API_URL: ${env:LOGS_API_URL, ssm:/greatupsells/${self:provider.stage}/logs-api/url}
    LOG_QUEUE_URL: ${ssm:/greatupsells/${self:provider.stage}/queues/log/url, ''}
    LOG_SOURCE: 'admin-api'
    SHOPS_API_URL: ${env:SHOPS_API_URL, ssm:/greatupsells/${self:provider.stage}/shops-api/url}

custom:
  serverless-offline:
    httpPort: ${env:ADMIN_API_PORT, 4005}
    lambdaPort: 4105
  customDomain:
    domainName: ${ssm:/greatupsells/${self:provider.stage}/admin-api/domain, ''}
    basePath: ''
    certificateName: ${ssm:/greatupsells/${self:provider.stage}/certificate-name, ''}
    createRoute53Record: true
    endpointType: regional
    route53Params:
      routingPolicy: latency
      setIdentifier: ${self:provider.region}
      healthCheckId: ${ssm:/greatupsells/${self:provider.stage}/admin-api/health-check-id, ''}
    securityPolicy: tls_1_2
    autoDomain: true
  warmup:
    default:
      enabled: true
      memorySize: 128
      concurrency: 1
      prewarm: true
      events:
        - schedule: rate(5 minutes)

functions:
  # authorizer:
  #   handler: src/authorizer.handler
  health:
    memorySize: 128
    handler: src/routes/health.handler
    events:
      - httpApi:
          path: /health
          method: get
  region:
    memorySize: 128
    handler: src/routes/region.handler
    events:
      - httpApi:
          path: /region
          method: get
    warmup:
      default:
        enabled: false
  # findLogs:
  findLogs:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/findLogs.handler
    events:
      - httpApi:
          path: /logs
          method: get
          # authorizer:
          #   name: authorizer
          #   type: request
          #   identitySource: method.request.header.Authorization
          #   resultTtlInSeconds: 0
  # findShops:
  # findStats:
plugins:
  - serverless-offline
  - serverless-plugin-monorepo
  - serverless-domain-manager
  - serverless-plugin-warmup

package:
  patterns:
    - '!infrastructure/**'
    - '!node_modules/**/*.map'
    - '!node_modules/**/aws-sdk'
    - '!node_modules/aws-sdk'
    - '!node_modules/eslint'
