service: upselling-shopify-admin

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 10
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  environment:
    NODE_ENV: 'production'
    SHOPIFY_APP_URL: ${ssm:/upselling/${self:provider.stage}/shopify-app/url}
    API_URL: ${ssm:/upselling/${self:provider.stage}/api/url}
    MONGODB_URI: ${ssm:/upselling/${self:provider.stage}/database/mongodb/uri~true}

functions:
  health:
    memorySize: 128
    handler: server/health.handler
    events:
      - http:
          path: /health
          method: get
  region:
    memorySize: 128
    handler: server/region.handler
    events:
      - http:
          path: /region
          method: get
  server:
    handler: server/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${ssm:/upselling/${self:provider.stage}/shopify-app/endpoint/${self:provider.region}}
    basePath: ''
    certificateName: ${ssm:/upselling/${self:provider.stage}/certificate-name}
    createRoute53Record: true
    endpointType: regional
    securityPolicy: tls_1_2

package:
  exclude:
    - .terraform/**
    - test/**
    - node_modules/aws-sdk
    - node_modules/**/aws-sdk
    - node_modules/**/*.map
