service: greatupsells-shopify-admin
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 2048
  timeout: 10
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  httpApi:
    shouldStartNameWithService: true
    disableDefaultEndpoint: true
    cors: true
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    ASSETS_URL: ${env:ASSETS_URL, ssm:/greatupsells/${self:provider.stage}/assets/url}
    JWT_SECRET: ${env:JWT_SECRET, ssm:/greatupsells/${self:provider.stage}/jwt-secret}
    REDIS_URL_APP: ${env:REDIS_URL_APP, ssm:/greatupsells/${self:provider.stage}/database/redis-app/url}
    SHOPIFY_ADMIN_API_URL: ${env:SHOPIFY_ADMIN_API_URL, ssm:/greatupsells/${self:provider.stage}/shopify-admin-api/url}
    SHOPIFY_ADMIN_APP_API_KEY: ${env:SHOPIFY_ADMIN_APP_API_KEY, ssm:/greatupsells/${self:provider.stage}/shopify/api-key}
    SHOPIFY_ADMIN_APP_API_SECRET_KEY: ${env:SHOPIFY_ADMIN_APP_API_SECRET_KEY, ssm:/greatupsells/${self:provider.stage}/shopify/api-secret-key}
    SHOPIFY_ADMIN_APP_URL: ${env:SHOPIFY_ADMIN_APP_URL, ssm:/greatupsells/${self:provider.stage}/shopify-admin-app/url}
    SHOPIFY_EMBED_BLOCK_ID: ${env:SHOPIFY_EMBED_BLOCK_ID, ssm:/greatupsells/${self:provider.stage}/shopify/app-embed-block/id}
    SHOPS_API_URL: ${env:SHOPS_API_URL, ssm:/greatupsells/${self:provider.stage}/shops-api/url}
    LOG_SOURCE: 'shopify-admin'

custom:
  customDomain:
    domainName: ${ssm:/greatupsells/${self:provider.stage}/shopify-admin-app/latency-domain}
    basePath: ''
    certificateName: ${ssm:/greatupsells/${self:provider.stage}/certificate-name, ''}
    createRoute53Record: true
    endpointType: regional
    route53Params:
      routingPolicy: latency
      setIdentifier: ${self:provider.region}
      healthCheckId: ${ssm:/greatupsells/${self:provider.stage}/shopify-admin-app/health-check-id, ''}
    securityPolicy: tls_1_2
    autoDomain: true
  warmup:
    default:
      enabled: true
      memorySize: 256
      concurrency: 5
      prewarm: true
      events:
        - schedule: rate(5 minutes)

functions:
  health:
    memorySize: 128
    handler: src/routes/health.handler
    events:
      - httpApi:
          path: /health
          method: get
  region:
    memorySize: 128
    handler: src/routes/region.handler
    events:
      - httpApi:
          path: /region
          method: get
    warmup:
      default:
        enabled: false
  server:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/greatupsells/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/server.handler
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{any+}
          method: ANY
    timeout: 20

plugins:
  - serverless-plugin-monorepo
  - serverless-domain-manager
  - serverless-plugin-warmup

package:
  patterns:
    - '!infrastructure/**'
    - '!.next/cache/webpack/**'
    - '!node_modules/**/*.map'
    - '!node_modules/**/aws-sdk'
    - '!node_modules/aws-sdk'
    - '!node_modules/eslint'
