service: upselling-admin
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  timeout: 10
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    shouldStartNameWithService: true
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    ADMIN_API_URL: ${env:ADMIN_API_URL, ssm:/upselling/${self:provider.stage}/admin-api/url}
    ASSETS_URL: ${env:ASSETS_URL, ssm:/upselling/${self:provider.stage}/assets/url}
    JWT_SECRET: ${env:JWT_SECRET, ssm:/upselling/${self:provider.stage}/jwt-secret~true}
    SHOPS_API_URL: ${env:SHOPS_API_URL, ssm:/upselling/${self:provider.stage}/shops-api/url}

custom:
  customDomain:
    domainName: ${ssm:/upselling/${self:provider.stage}/admin-app/domain}
    basePath: ''
    certificateName: ${env:CERTIFICATE_NAME, ssm:/upselling/${self:provider.stage}/certificate-name}
    createRoute53Record: true
    endpointType: regional
    route53Params:
      routingPolicy: latency
      setIdentifier: ${self:provider.region}
      healthCheckId: ${ssm:/upselling/${self:provider.stage}/admin-app/health-check-id}
    securityPolicy: tls_1_2
    autoDomain: true
  warmup:
    default:
      enabled: true
      concurrency: 5
      prewarm: true
      events:
        - schedule: rate(5 minutes)

functions:
  health:
    memorySize: 128
    handler: src/routes/health.handler
    events:
      - http:
          path: /health
          method: get
          cors: true
    warmup:
      default:
        enabled: true
  region:
    memorySize: 128
    handler: src/routes/region.handler
    events:
      - http:
          path: /region
          method: get
          cors: true
  server:
    role: ${env:SERVICES_CONSUMER_ROLE_ARN, ssm:/upselling/${self:provider.stage}/roles/services-consumer-arn}
    handler: src/routes/server.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
    warmup:
      default:
        enabled: true

plugins:
  - serverless-plugin-monorepo
  - serverless-domain-manager
  - serverless-plugin-warmup

package:
  exclude:
    - infrastructure/**
    - .next/cache/webpack/**
