certificate_name = "*.greatupsells.com"
hosted_zone_id   = "Z023060413ODYTHFNWZW8"
domain           = "greatupsells.com"
instance_type    = "t3a.medium"
sandbox          = "false"
jwt_secret       = "2ab8c99671a507f3314818894cad27ed562552a29713eda67f7b2dbdf81e13e0"
services_domain_names = {
  "us-east-1"      = "services.us-east-1.greatupsells.com"
  "us-west-2"      = "services.us-west-2.greatupsells.com"
  "us-east-2"      = "services.us-east-2.greatupsells.com"
  "eu-west-1"      = "services.eu-west-1.greatupsells.com"
  "ap-northeast-1" = "services.ap-northeast-1.greatupsells.com"
}
shopify_admin_app_api_key        = ""
shopify_admin_app_api_secret_key = ""
shopify_admin_app_url            = "shopify-admin.greatupsells.com"
event_bus_arn                    = ""
