app_name      = "Great Upsells"
app_name_slug = "great-upsells"
base_domain   = "greatupsells.com"
domain        = "greatupsells.com"
instance_type = "t3.large"
sandbox       = "false"
jwt_secret    = "2ab8c99671a507f3314818894cad27ed562552a29713eda67f7b2dbdf81e13e0"
services_domains = {
  "us-east-1"      = "services.greatupsells.com"
  # "eu-west-1"      = "services.eu-west-1.greatupsells.com"
  # "ap-northeast-1" = "services.ap-northeast-1.greatupsells.com"
}
assets_domain                    = "assets.greatupsells.com"
shopify_admin_app_api_key        = "33815daf9e7d64650743e8b9b4e793c5"
shopify_post_purchase_id         = "PLACEHOLDER"
event_bus_arn                    = "arn:aws:events:us-east-1::event-source/aws.partner/shopify.com/238899593217/greatupsells-webhooks-prod"
health_check_alarm_email         = "greatupsells@proxima.ai"
