name: greatupsells-email-service
on:
  push:
    branches:
      - test
      - production
    paths:
      - .github/workflows/email-service.yml
      - services/email/**
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - name: Set Environment Variables
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: yarn
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Node Modules
        run: yarn install --immutable
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Install Global Packages
        run: npm install -g serverless@3.38.0
      - name: Run Terraform
        run: yarn infrastructure
        working-directory: services/email
        env:
          STAGE: ${{ env.BRANCH }}
      - name: Build Packages
        run: yarn workspaces focus --all && NODE_ENV=production lerna run build --stream --scope=@greatupsells/*
      - name: Download .serverless directory
        run: aws s3 sync s3://greatupsells-infrastructure2/serverless/email-service . --region us-east-1
        working-directory: services/email
      - name: Deploy Serverless Application to us-east-1
        run: serverless deploy --stage $BRANCH --region us-east-1
        working-directory: services/email
      # - name: Deploy Serverless Application to eu-west-1
      #   run: serverless deploy --stage $BRANCH --region eu-west-1
      #   working-directory: services/email
      #   if: ${{ github.ref == 'refs/heads/master' }}
      # - name: Deploy Serverless Application to ap-northeast-1
      #   run: serverless deploy --stage $BRANCH --region ap-northeast-1
      #   working-directory: services/email
      #   if: ${{ github.ref == 'refs/heads/master' }}
      - name: Sync .serverless directory
        run: aws s3 sync .serverless s3://greatupsells-infrastructure2/serverless/email-service/.serverless --region us-east-1
        working-directory: services/email
      - name: Uninstall Global Packages
        if: always()
        run: npm uninstall -g serverless
