name: upselling-infrastructure
on:
  push:
    branches:
      - test
      - production
    paths:
      - .github/workflows/infrastructure.yml
      - infrastructure/**
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Set Environment Variables
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Install Private Key
        run: |
          mkdir -p ~/.ssh/neatowebsolutions
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/neatowebsolutions/id_rsa
          chmod 600 ~/.ssh/neatowebsolutions/id_rsa
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Lambda Resources
        run: zip host-lambda.zip host-lambda.js
        working-directory: infrastructure
      - name: Add Terraform variables
        run: |
          echo -e "\naws_access_key_id: \"${{ secrets.AWS_ACCESS_KEY_ID_SERVER }}\"" >> ./infrastructure/region/services-server/roles/common/vars/main.yml
          echo -e "\naws_secret_access_key: \"${{ secrets.AWS_SECRET_ACCESS_KEY_SERVER }}\"" >> ./infrastructure/region/services-server/roles/common/vars/main.yml
          echo -e "\nmongodb_root_password: \"${{ secrets.MONGODB_ROOT_PASSWORD }}\"" >> ./infrastructure/region/services-server/roles/mongodb/vars/main.yml
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Install Ansible
        run: sudo apt-get install ansible
      - name: Run Terraform
        run: STAGE=$BRANCH ./run.sh
        working-directory: infrastructure
