name: greatupsells-shopify-admin
on:
  push:
    branches:
      - test
      - production
    paths:
      - .github/workflows/shopify-admin.yml
      - applications/shopify-admin/**
      - packages/gateway-http-client/**
      - packages/react-components/**
      - packages/react-hooks/**
      - packages/themes/**
      - packages/themes-admin/**
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
    steps:
      - name: Set Environment Variables
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
      - name: Inject "ASSETS_DOMAIN" SSM Parameter
        uses: 'marvinpinto/action-inject-ssm-secrets@latest'
        with:
          ssm_parameter: '/greatupsells/${{ env.BRANCH }}/assets/domain'
          env_variable_name: 'ASSETS_DOMAIN'
      - name: Inject "ASSETS_URL" SSM Parameter
        uses: 'marvinpinto/action-inject-ssm-secrets@latest'
        with:
          ssm_parameter: '/greatupsells/${{ env.BRANCH }}/assets/url'
          env_variable_name: 'ASSETS_URL'
      - name: Inject "SHOPIFY_ADMIN_APP_API_KEY" SSM Parameter
        uses: 'marvinpinto/action-inject-ssm-secrets@latest'
        with:
          ssm_parameter: '/greatupsells/${{ env.BRANCH }}/shopify/api-key'
          env_variable_name: 'SHOPIFY_ADMIN_APP_API_KEY'
      - name: Inject "SHOPIFY_ADMIN_API_URL" SSM Parameter
        uses: 'marvinpinto/action-inject-ssm-secrets@latest'
        with:
          ssm_parameter: '/greatupsells/${{ env.BRANCH }}/shopify-admin-api/url'
          env_variable_name: 'SHOPIFY_ADMIN_API_URL'
      - name: Inject "STOREFRONT_API_URL" SSM Parameter
        uses: 'marvinpinto/action-inject-ssm-secrets@latest'
        with:
          ssm_parameter: '/greatupsells/${{ env.BRANCH }}/storefront-api/url'
          env_variable_name: 'STOREFRONT_API_URL'

      # Specific to app extensions.
      - name: Inject "SHOPIFY_API_KEY" SSM Parameter
        uses: 'marvinpinto/action-inject-ssm-secrets@latest'
        with:
          ssm_parameter: '/greatupsells/${{ env.BRANCH }}/shopify/api-key'
          env_variable_name: 'SHOPIFY_API_KEY'
      - name: Inject "SHOPIFY_POST_PURCHASE_UPSELLS_ID" SSM Parameter
        uses: 'marvinpinto/action-inject-ssm-secrets@latest'
        with:
          ssm_parameter: '/greatupsells/${{ env.BRANCH }}/shopify/post-purchase/id'
          env_variable_name: 'SHOPIFY_POST_PURCHASE_UPSELLS_ID'

      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: yarn
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Node Modules
        run: yarn install --immutable
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Install Global Packages
        run: npm install -g serverless@3.38.0
      - name: Run Terraform
        run: yarn infrastructure
        working-directory: applications/shopify-admin
        env:
          STAGE: ${{ env.BRANCH }}
      - name: Build Packages
        run: yarn workspaces focus --all && NODE_ENV=production lerna run build --stream --scope=@greatupsells/*
      - name: Download .serverless directory
        run: aws s3 sync s3://greatupsells-infrastructure2/serverless/shopify-admin . --region us-east-1
        working-directory: applications/shopify-admin
      - name: Build Next.js Application
        run: NODE_ENV=production yarn build
        working-directory: applications/shopify-admin
      - name: Upload Next.js Static Assets to Assets Bucket
        run: aws s3 sync applications/shopify-admin/.next/static s3://$ASSETS_DOMAIN/shopify-admin/_next/static --cache-control immutable,max-age=31536000,public --region us-east-1
      - name: Upload Next.js Public Assets to Assets Bucket
        run: aws s3 sync applications/shopify-admin/public s3://$ASSETS_DOMAIN/shopify-admin --cache-control immutable,max-age=31536000,public --region us-east-1
      - name: Deploy Serverless Application to us-east-1
        run: serverless deploy --stage $BRANCH --region us-east-1
        working-directory: applications/shopify-admin
      # - name: Deploy Serverless Application to eu-west-1
      #   run: serverless deploy --stage $BRANCH --region eu-west-1
      #   working-directory: applications/shopify-admin
      #   if: ${{ github.ref == 'refs/heads/master' }}
      # - name: Deploy Serverless Application to ap-northeast-1
      #   run: serverless deploy --stage $BRANCH --region ap-northeast-1
      #   working-directory: applications/shopify-admin
      #   if: ${{ github.ref == 'refs/heads/master' }}
      - name: Sync .serverless directory
        run: aws s3 sync .serverless s3://greatupsells-infrastructure2/serverless/shopify-admin/.serverless
        working-directory: applications/shopify-admin
      - name: Publish Shopify extensions (test)
        if: ${{ success() && github.ref == 'refs/heads/test' }}
        run: env > .env && yarn extensions:deploy -c test
        working-directory: applications/shopify-admin
        env:
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN_TEST }}
      - name: Publish Shopify extensions (production)
        if: ${{ success() && github.ref == 'refs/heads/master' }}
        run: env > .env && yarn extensions:deploy -c production
        working-directory: applications/shopify-admin
        env:
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
      - name: Uninstall Global Packages
        if: always()
        run: npm uninstall -g serverless
