name: upselling-storefront-api
on:
  push:
    branches:
      - test
      - production
    paths:
      - .github/workflows/storefront-api.yml
      - services/storefront-api/**
      - packages/logger/**
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Set Environment Variables
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Install Global Packages
        run: npm install -g yarn serverless
      - name: Run Terraform
        run: (cd ./services/storefront-api/infrastructure && STAGE=$BRANCH ./run.sh)
      - name: Install Node Modules
        run: yarn install
      - name: Deploy Serverless Application (us-east-1)
        run: AWS_REGION=us-east-1 serverless deploy -s $BRANCH
        working-directory: services/storefront-api
      - name: Uninstall Global Packages
        if: always()
        run: npm uninstall -g yarn serverless
