name: upselling-storefront
on:
  push:
    branches:
      - test
      - production
    paths:
      - .github/workflows/storefront.yml
      - applications/storefront/**
      - packages/**
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - name: Set Environment Variables
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Inject "STOREFRONT_API_URL" SSM Parameter
        uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "/upselling/${{ env.BRANCH }}/storefront-api/url"
          env_variable_name: "STOREFRONT_API_URL"
      - name: Inject "ASSETS_DOMAIN" SSM Parameter
        uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "/upselling/${{ env.BRANCH }}/assets/domain"
          env_variable_name: "ASSETS_DOMAIN"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      - name: Install Global Packages
        run: npm install -g yarn
      - name: Install Node Modules
        run: yarn install
      - name: Build Packages
        run: lerna bootstrap --force-local && lerna run build --stream --scope=@neatowebsolutions/*
      - name: Build Application
        run: yarn build
        working-directory: applications/storefront
      - name: Upload Application to Assets Bucket
        run: aws s3 sync applications/storefront/dist/ s3://$ASSETS_DOMAIN --cache-control public,must-revalidate,proxy-revalidate,max-age=0,s-maxage=0 --storage-class STANDARD_IA
      - name: Uninstall Global Packages
        if: always()
        run: npm uninstall -g yarn serverless
