name: greatupsells-webhooks-service
on:
  push:
    branches:
      - test
      - production
    paths:
      - .github/workflows/webhooks-service.yml
      - services/webhooks/**
      - packages/logger/**
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Set Environment Variables
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
          cache: yarn
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Install Global Packages
        run: npm install -g serverless
      - name: Run Terraform
        run: yarn infrastructure
        working-directory: services/webhooks
        env:
          STAGE: ${{ env.BRANCH }}
      - name: Install Node Modules
        run: yarn install --immutable
      - name: Build Packages
        run: lerna bootstrap --force-local && NODE_ENV=production lerna run build --stream --scope=@greatupsells/*
      - name: Download .serverless directory
        run: aws s3 sync s3://greatupsells-infrastructure2/serverless/webhooks-service . --region us-east-1
        working-directory: services/webhooks
      - name: Deploy Serverless Application (us-east-1)
        run: serverless deploy --stage $BRANCH --region us-east-1
        working-directory: services/webhooks
      - name: Sync .serverless directory
        run: aws s3 sync .serverless s3://greatupsells-infrastructure2/serverless/webhooks-service/.serverless --region us-east-1
        working-directory: services/webhooks
      - name: Uninstall Global Packages
        if: always()
        run: npm uninstall -g serverless
